# Generated by Django 5.2.8 on 2025-12-10 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0003_team_billing_details_last_changed_team_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('display_name', models.CharField(max_length=255)),
                ('github_username', models.CharField(blank=True, max_length=100)),
                ('github_id', models.CharField(blank=True, max_length=50)),
                ('jira_account_id', models.CharField(blank=True, max_length=100)),
                ('slack_user_id', models.CharField(blank=True, max_length=50)),
                ('role', models.CharField(choices=[('developer', 'Developer'), ('lead', 'Lead'), ('admin', 'Admin')], default='developer', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('github_id__gt', '')), fields=('team', 'github_id'), name='unique_team_github_id'), models.UniqueConstraint(condition=models.Q(('email__gt', '')), fields=('team', 'email'), name='unique_team_email')],
            },
        ),
    ]
