# Generated by Django 5.2.9 on 2025-12-13 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', 'backfill_jira_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='prsurvey',
            name='github_comment_id',
            field=models.BigIntegerField(blank=True, help_text='The GitHub comment ID where the survey was posted', null=True, verbose_name='GitHub Comment ID'),
        ),
        migrations.AddField(
            model_name='prsurvey',
            name='token',
            field=models.CharField(blank=True, db_index=True, help_text='Unique token for accessing the survey via URL', max_length=64, null=True, unique=True, verbose_name='Token'),
        ),
        migrations.AddField(
            model_name='prsurvey',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, help_text='When the survey token expires', null=True, verbose_name='Token Expires At'),
        ),
    ]
