# Generated by Django 5.2.9 on 2025-12-13 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0001_prsurvey_github_comment_id_prsurvey_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prsurvey',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When the survey token expires (typically 7 days after creation)', null=True, verbose_name='Token Expires At'),
        ),
    ]
