# Generated by Django 5.2.8 on 2025-12-10 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['display_name'], 'verbose_name': 'Team Member', 'verbose_name_plural': 'Team Members'},
        ),
        migrations.AlterField(
            model_name='teammember',
            name='display_name',
            field=models.CharField(help_text="How this team member's name is displayed", max_length=255, verbose_name='Display name'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='email',
            field=models.EmailField(blank=True, help_text="Team member's email address", max_length=254, verbose_name='Email address'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='github_id',
            field=models.CharField(blank=True, db_index=True, help_text='GitHub user ID for this team member', max_length=50, verbose_name='GitHub ID'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='github_username',
            field=models.CharField(blank=True, db_index=True, help_text='GitHub username for this team member', max_length=100, verbose_name='GitHub username'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this team member is currently active', verbose_name='Active status'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='jira_account_id',
            field=models.CharField(blank=True, db_index=True, help_text='Jira account ID for this team member', max_length=100, verbose_name='Jira account ID'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(choices=[('developer', 'Developer'), ('lead', 'Lead'), ('admin', 'Admin')], default='developer', help_text="Team member's role", max_length=20, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='slack_user_id',
            field=models.CharField(blank=True, db_index=True, help_text='Slack user ID for this team member', max_length=50, verbose_name='Slack user ID'),
        ),
    ]
