# Generated by Django 5.2.8 on 2025-12-10 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0002_alter_teammember_options_and_more'),
        ('teams', '0003_team_billing_details_last_changed_team_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PullRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('github_pr_id', models.BigIntegerField(help_text='The PR number from GitHub', verbose_name='GitHub PR ID')),
                ('github_repo', models.CharField(help_text="Repository name (e.g., 'owner/repo')", max_length=255, verbose_name='GitHub repository')),
                ('title', models.TextField(blank=True, help_text='The title of the pull request', verbose_name='PR title')),
                ('state', models.CharField(choices=[('open', 'Open'), ('merged', 'Merged'), ('closed', 'Closed')], help_text='Current state of the PR', max_length=20, verbose_name='State')),
                ('pr_created_at', models.DateTimeField(blank=True, help_text='When the PR was created', null=True, verbose_name='PR created at')),
                ('merged_at', models.DateTimeField(blank=True, help_text='When the PR was merged', null=True, verbose_name='Merged at')),
                ('first_review_at', models.DateTimeField(blank=True, help_text='When the first review was submitted', null=True, verbose_name='First review at')),
                ('cycle_time_hours', models.DecimalField(blank=True, decimal_places=2, help_text='Time from PR creation to merge', max_digits=10, null=True, verbose_name='Cycle time (hours)')),
                ('review_time_hours', models.DecimalField(blank=True, decimal_places=2, help_text='Time from PR creation to first review', max_digits=10, null=True, verbose_name='Review time (hours)')),
                ('additions', models.IntegerField(default=0, help_text='Lines added in this PR', verbose_name='Additions')),
                ('deletions', models.IntegerField(default=0, help_text='Lines deleted in this PR', verbose_name='Deletions')),
                ('is_revert', models.BooleanField(default=False, help_text='Whether this is a revert PR', verbose_name='Is revert')),
                ('is_hotfix', models.BooleanField(default=False, help_text='Whether this is a hotfix PR', verbose_name='Is hotfix')),
                ('synced_at', models.DateTimeField(auto_now=True, help_text='Last time this PR data was synced', verbose_name='Synced at')),
                ('author', models.ForeignKey(help_text='The team member who created the PR', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pull_requests', to='metrics.teammember', verbose_name='Author')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'verbose_name': 'Pull Request',
                'verbose_name_plural': 'Pull Requests',
                'ordering': ['-pr_created_at'],
            },
        ),
        migrations.CreateModel(
            name='PRReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('approved', 'Approved'), ('changes_requested', 'Changes Requested'), ('commented', 'Commented')], help_text='The review state', max_length=20, verbose_name='State')),
                ('submitted_at', models.DateTimeField(blank=True, help_text='When the review was submitted', null=True, verbose_name='Submitted at')),
                ('reviewer', models.ForeignKey(help_text='The team member who submitted the review', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews_given', to='metrics.teammember', verbose_name='Reviewer')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
                ('pull_request', models.ForeignKey(help_text='The PR being reviewed', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='metrics.pullrequest', verbose_name='Pull request')),
            ],
            options={
                'verbose_name': 'PR Review',
                'verbose_name_plural': 'PR Reviews',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('github_sha', models.CharField(help_text='The commit SHA from GitHub', max_length=40, verbose_name='GitHub SHA')),
                ('github_repo', models.CharField(help_text="Repository name (e.g., 'owner/repo')", max_length=255, verbose_name='GitHub repository')),
                ('message', models.TextField(blank=True, help_text='The commit message', verbose_name='Commit message')),
                ('additions', models.IntegerField(default=0, help_text='Lines added in this commit', verbose_name='Additions')),
                ('deletions', models.IntegerField(default=0, help_text='Lines deleted in this commit', verbose_name='Deletions')),
                ('committed_at', models.DateTimeField(blank=True, help_text='When the commit was made', null=True, verbose_name='Committed at')),
                ('author', models.ForeignKey(help_text='The team member who authored the commit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commits', to='metrics.teammember', verbose_name='Author')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
                ('pull_request', models.ForeignKey(blank=True, help_text='The PR this commit belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commits', to='metrics.pullrequest', verbose_name='Pull request')),
            ],
            options={
                'verbose_name': 'Commit',
                'verbose_name_plural': 'Commits',
                'ordering': ['-committed_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='pullrequest',
            constraint=models.UniqueConstraint(fields=('team', 'github_pr_id', 'github_repo'), name='unique_team_pr'),
        ),
        migrations.AddConstraint(
            model_name='commit',
            constraint=models.UniqueConstraint(fields=('team', 'github_sha'), name='unique_team_commit'),
        ),
    ]
