# Generated by Django 5.2.9 on 2025-12-20 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0002_alter_prsurvey_token_expires_at'),
        ('teams', '0003_team_billing_details_last_changed_team_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PRCheckRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('github_check_run_id', models.BigIntegerField(help_text='The check run ID from GitHub', verbose_name='GitHub Check Run ID')),
                ('name', models.CharField(help_text='Name of the check (e.g., pytest, eslint, build)', max_length=255, verbose_name='Check name')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('in_progress', 'In Progress'), ('completed', 'Completed')], help_text='Current status of the check run', max_length=20, verbose_name='Status')),
                ('conclusion', models.CharField(blank=True, choices=[('success', 'Success'), ('failure', 'Failure'), ('skipped', 'Skipped'), ('cancelled', 'Cancelled'), ('timed_out', 'Timed Out'), ('action_required', 'Action Required'), ('neutral', 'Neutral'), ('stale', 'Stale')], help_text='Final conclusion of the check run', max_length=20, null=True, verbose_name='Conclusion')),
                ('started_at', models.DateTimeField(blank=True, help_text='When the check run started', null=True, verbose_name='Started at')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the check run completed', null=True, verbose_name='Completed at')),
                ('duration_seconds', models.IntegerField(blank=True, help_text='How long the check run took', null=True, verbose_name='Duration (seconds)')),
                ('pull_request', models.ForeignKey(help_text='The PR this check run belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='check_runs', to='metrics.pullrequest', verbose_name='Pull request')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'verbose_name': 'PR Check Run',
                'verbose_name_plural': 'PR Check Runs',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['pull_request', 'name'], name='check_run_pr_name_idx')],
                'constraints': [models.UniqueConstraint(fields=('team', 'github_check_run_id'), name='unique_team_check_run')],
            },
        ),
    ]
