# Generated by Django 5.2.9 on 2025-12-20 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0003_prcheckrun'),
        ('teams', '0003_team_billing_details_last_changed_team_customer_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='prcheckrun',
            index=models.Index(fields=['started_at'], name='check_run_started_at_idx'),
        ),
    ]
