# Generated by Django 5.2.8 on 2025-12-10 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0003_pullrequest_prreview_commit_and_more'),
        ('teams', '0003_team_billing_details_last_changed_team_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JiraIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jira_key', models.CharField(help_text='e.g., PROJ-123', max_length=50, verbose_name='Jira Key')),
                ('jira_id', models.CharField(help_text="Jira's internal ID", max_length=50, verbose_name='Jira ID')),
                ('summary', models.TextField(blank=True, verbose_name='Summary')),
                ('issue_type', models.CharField(blank=True, help_text='Story, Bug, Task, etc.', max_length=50, verbose_name='Issue Type')),
                ('status', models.CharField(blank=True, max_length=50, verbose_name='Status')),
                ('story_points', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Story Points')),
                ('sprint_id', models.CharField(blank=True, max_length=50, verbose_name='Sprint ID')),
                ('sprint_name', models.CharField(blank=True, max_length=255, verbose_name='Sprint Name')),
                ('issue_created_at', models.DateTimeField(blank=True, null=True, verbose_name='Created At')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resolved At')),
                ('cycle_time_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cycle Time (hours)')),
                ('synced_at', models.DateTimeField(auto_now=True, verbose_name='Last Synced')),
            ],
            options={
                'verbose_name': 'Jira Issue',
                'verbose_name_plural': 'Jira Issues',
                'ordering': ['-issue_created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='commit',
            index=models.Index(fields=['github_repo', 'committed_at'], name='commit_repo_date_idx'),
        ),
        migrations.AddIndex(
            model_name='commit',
            index=models.Index(fields=['author', 'committed_at'], name='commit_author_date_idx'),
        ),
        migrations.AddIndex(
            model_name='commit',
            index=models.Index(fields=['pull_request'], name='commit_pr_idx'),
        ),
        migrations.AddIndex(
            model_name='prreview',
            index=models.Index(fields=['pull_request', 'submitted_at'], name='review_pr_submitted_idx'),
        ),
        migrations.AddIndex(
            model_name='prreview',
            index=models.Index(fields=['reviewer', 'state'], name='review_reviewer_state_idx'),
        ),
        migrations.AddIndex(
            model_name='pullrequest',
            index=models.Index(fields=['github_repo', 'state'], name='pr_repo_state_idx'),
        ),
        migrations.AddIndex(
            model_name='pullrequest',
            index=models.Index(fields=['author', 'state'], name='pr_author_state_idx'),
        ),
        migrations.AddIndex(
            model_name='pullrequest',
            index=models.Index(fields=['merged_at'], name='pr_merged_at_idx'),
        ),
        migrations.AddIndex(
            model_name='pullrequest',
            index=models.Index(fields=['pr_created_at'], name='pr_created_at_idx'),
        ),
        migrations.AddField(
            model_name='jiraissue',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jira_issues', to='metrics.teammember'),
        ),
        migrations.AddField(
            model_name='jiraissue',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team'),
        ),
        migrations.AddIndex(
            model_name='jiraissue',
            index=models.Index(fields=['jira_key'], name='metrics_jir_jira_ke_a6f759_idx'),
        ),
        migrations.AddIndex(
            model_name='jiraissue',
            index=models.Index(fields=['resolved_at'], name='metrics_jir_resolve_a3fe97_idx'),
        ),
        migrations.AddIndex(
            model_name='jiraissue',
            index=models.Index(fields=['assignee', 'status'], name='metrics_jir_assigne_a76723_idx'),
        ),
        migrations.AddIndex(
            model_name='jiraissue',
            index=models.Index(fields=['sprint_id'], name='metrics_jir_sprint__6eda31_idx'),
        ),
        migrations.AddConstraint(
            model_name='jiraissue',
            constraint=models.UniqueConstraint(fields=('team', 'jira_id'), name='unique_team_jira_issue'),
        ),
    ]
