# Generated by Django 5.2.8 on 2025-12-10 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0004_jiraissue_commit_commit_repo_date_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='jiraissue',
            new_name='jira_issue_key_idx',
            old_name='metrics_jir_jira_ke_a6f759_idx',
        ),
        migrations.RenameIndex(
            model_name='jiraissue',
            new_name='jira_resolved_at_idx',
            old_name='metrics_jir_resolve_a3fe97_idx',
        ),
        migrations.RenameIndex(
            model_name='jiraissue',
            new_name='jira_assignee_status_idx',
            old_name='metrics_jir_assigne_a76723_idx',
        ),
        migrations.RenameIndex(
            model_name='jiraissue',
            new_name='jira_sprint_idx',
            old_name='metrics_jir_sprint__6eda31_idx',
        ),
        migrations.AlterField(
            model_name='jiraissue',
            name='assignee',
            field=models.ForeignKey(blank=True, help_text='The team member assigned to this issue', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jira_issues', to='metrics.teammember', verbose_name='Assignee'),
        ),
        migrations.AlterField(
            model_name='jiraissue',
            name='cycle_time_hours',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Time from creation to resolution', max_digits=10, null=True, verbose_name='Cycle Time (hours)'),
        ),
        migrations.AlterField(
            model_name='jiraissue',
            name='issue_created_at',
            field=models.DateTimeField(blank=True, help_text='When the issue was created in Jira', null=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='jiraissue',
            name='resolved_at',
            field=models.DateTimeField(blank=True, help_text='When the issue was resolved', null=True, verbose_name='Resolved At'),
        ),
        migrations.AlterField(
            model_name='jiraissue',
            name='sprint_id',
            field=models.CharField(blank=True, help_text='The sprint this issue belongs to', max_length=50, verbose_name='Sprint ID'),
        ),
        migrations.AlterField(
            model_name='jiraissue',
            name='sprint_name',
            field=models.CharField(blank=True, help_text='Human-readable sprint name', max_length=255, verbose_name='Sprint Name'),
        ),
        migrations.AlterField(
            model_name='jiraissue',
            name='status',
            field=models.CharField(blank=True, help_text='Current issue status', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='jiraissue',
            name='story_points',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Estimated story points', max_digits=5, null=True, verbose_name='Story Points'),
        ),
        migrations.AlterField(
            model_name='jiraissue',
            name='summary',
            field=models.TextField(blank=True, help_text='Issue summary/title', verbose_name='Summary'),
        ),
        migrations.AlterField(
            model_name='jiraissue',
            name='synced_at',
            field=models.DateTimeField(auto_now=True, help_text='Last time this issue data was synced', verbose_name='Synced at'),
        ),
    ]
