# Generated by Django 5.2.9 on 2025-12-20 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0004_prcheckrun_check_run_started_at_idx'),
        ('teams', '0003_team_billing_details_last_changed_team_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PRFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filename', models.CharField(help_text='Path to the file', max_length=500, verbose_name='Filename')),
                ('status', models.CharField(choices=[('added', 'Added'), ('modified', 'Modified'), ('removed', 'Removed'), ('renamed', 'Renamed')], help_text='File change status', max_length=20, verbose_name='Status')),
                ('additions', models.IntegerField(default=0, help_text='Lines added', verbose_name='Additions')),
                ('deletions', models.IntegerField(default=0, help_text='Lines deleted', verbose_name='Deletions')),
                ('changes', models.IntegerField(default=0, help_text='Total changes', verbose_name='Changes')),
                ('file_category', models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('test', 'Test'), ('docs', 'Documentation'), ('config', 'Configuration'), ('other', 'Other')], help_text='Categorized file type', max_length=50, verbose_name='File category')),
                ('pull_request', models.ForeignKey(help_text='The PR this file belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='files', to='metrics.pullrequest', verbose_name='Pull request')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'verbose_name': 'PR File',
                'verbose_name_plural': 'PR Files',
                'ordering': ['filename'],
                'indexes': [models.Index(fields=['pull_request', 'file_category'], name='pr_file_category_idx')],
                'constraints': [models.UniqueConstraint(fields=('team', 'pull_request', 'filename'), name='unique_team_pr_file')],
            },
        ),
    ]
