# Generated by Django 5.2.8 on 2025-12-10 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0005_rename_metrics_jir_jira_ke_a6f759_idx_jira_issue_key_idx_and_more'),
        ('teams', '0003_team_billing_details_last_changed_team_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PRSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author_ai_assisted', models.BooleanField(help_text='Whether the author used AI tools (null = not responded yet)', null=True, verbose_name='Author AI Assisted')),
                ('author_responded_at', models.DateTimeField(blank=True, help_text='When the author responded to the survey', null=True, verbose_name='Author Responded At')),
                ('author', models.ForeignKey(help_text='The PR author', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_surveys', to='metrics.teammember', verbose_name='Author')),
                ('pull_request', models.OneToOneField(help_text='The PR this survey is for', on_delete=django.db.models.deletion.CASCADE, related_name='survey', to='metrics.pullrequest', verbose_name='Pull Request')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'verbose_name': 'PR Survey',
                'verbose_name_plural': 'PR Surveys',
            },
        ),
        migrations.CreateModel(
            name='AIUsageDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(help_text='The date for this usage record', verbose_name='Date')),
                ('source', models.CharField(choices=[('copilot', 'GitHub Copilot'), ('cursor', 'Cursor')], help_text='AI tool source (Copilot, Cursor, etc.)', max_length=20, verbose_name='Source')),
                ('active_hours', models.DecimalField(blank=True, decimal_places=2, help_text='Hours the AI tool was active', max_digits=5, null=True, verbose_name='Active Hours')),
                ('suggestions_shown', models.IntegerField(default=0, help_text='Number of AI suggestions shown', verbose_name='Suggestions Shown')),
                ('suggestions_accepted', models.IntegerField(default=0, help_text='Number of AI suggestions accepted', verbose_name='Suggestions Accepted')),
                ('acceptance_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage of suggestions accepted', max_digits=5, null=True, verbose_name='Acceptance Rate')),
                ('synced_at', models.DateTimeField(auto_now=True, help_text='Last time this usage data was synced', verbose_name='Synced at')),
                ('member', models.ForeignKey(help_text='The team member who used the AI tool', on_delete=django.db.models.deletion.CASCADE, related_name='ai_usage', to='metrics.teammember', verbose_name='Team Member')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'verbose_name': 'AI Usage Daily',
                'verbose_name_plural': 'AI Usage Daily',
                'constraints': [models.UniqueConstraint(fields=('team', 'member', 'date', 'source'), name='unique_team_member_date_source')],
            },
        ),
        migrations.CreateModel(
            name='PRSurveyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quality_rating', models.IntegerField(choices=[(1, 'Could be better'), (2, 'OK'), (3, 'Super')], help_text="Reviewer's quality rating of the PR", null=True, verbose_name='Quality Rating')),
                ('ai_guess', models.BooleanField(help_text="Reviewer's guess whether AI was used", null=True, verbose_name='AI Guess')),
                ('guess_correct', models.BooleanField(help_text="Whether the reviewer's guess was correct", null=True, verbose_name='Guess Correct')),
                ('responded_at', models.DateTimeField(blank=True, help_text='When the reviewer responded', null=True, verbose_name='Responded At')),
                ('reviewer', models.ForeignKey(help_text='The reviewer providing feedback', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_reviews', to='metrics.teammember', verbose_name='Reviewer')),
                ('survey', models.ForeignKey(help_text='The survey this review is for', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='metrics.prsurvey', verbose_name='Survey')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'verbose_name': 'PR Survey Review',
                'verbose_name_plural': 'PR Survey Reviews',
                'constraints': [models.UniqueConstraint(fields=('survey', 'reviewer'), name='unique_survey_reviewer')],
            },
        ),
    ]
