# Generated by Django 5.2.9 on 2025-12-20 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0005_prfile'),
        ('teams', '0003_team_billing_details_last_changed_team_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('github_deployment_id', models.BigIntegerField(help_text='The deployment ID from GitHub', verbose_name='GitHub Deployment ID')),
                ('github_repo', models.CharField(help_text="Repository name (e.g., 'owner/repo')", max_length=255, verbose_name='GitHub repository')),
                ('environment', models.CharField(choices=[('production', 'Production'), ('staging', 'Staging')], help_text='Deployment environment', max_length=100, verbose_name='Environment')),
                ('status', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure'), ('pending', 'Pending'), ('error', 'Error')], help_text='Deployment status', max_length=20, verbose_name='Status')),
                ('deployed_at', models.DateTimeField(help_text='When the deployment occurred', verbose_name='Deployed at')),
                ('sha', models.CharField(help_text='The commit SHA deployed', max_length=40, verbose_name='Git SHA')),
                ('creator', models.ForeignKey(blank=True, help_text='The team member who created the deployment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deployments', to='metrics.teammember', verbose_name='Creator')),
                ('pull_request', models.ForeignKey(blank=True, help_text='The PR associated with this deployment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deployments', to='metrics.pullrequest', verbose_name='Pull request')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'verbose_name': 'Deployment',
                'verbose_name_plural': 'Deployments',
                'ordering': ['-deployed_at'],
                'indexes': [models.Index(fields=['github_repo', 'environment'], name='deployment_repo_env_idx'), models.Index(fields=['deployed_at'], name='deployment_deployed_at_idx'), models.Index(fields=['status'], name='deployment_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('team', 'github_deployment_id'), name='unique_team_deployment')],
            },
        ),
    ]
