# Generated by Django 5.2.9 on 2025-12-20 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0006_deployment'),
        ('teams', '0003_team_billing_details_last_changed_team_customer_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='deployment',
            index=models.Index(fields=['pull_request'], name='deployment_pr_idx'),
        ),
        migrations.AddIndex(
            model_name='deployment',
            index=models.Index(fields=['creator', 'status'], name='deployment_creator_status_idx'),
        ),
    ]
