# Generated by Django 5.2.8 on 2025-12-10 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0006_prsurvey_aiusagedaily_prsurveyreview'),
        ('teams', '0003_team_billing_details_last_changed_team_customer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aiusagedaily',
            options={'ordering': ['-date', 'member'], 'verbose_name': 'AI Usage Daily', 'verbose_name_plural': 'AI Usage Daily'},
        ),
        migrations.AlterModelOptions(
            name='prsurvey',
            options={'ordering': ['-created_at'], 'verbose_name': 'PR Survey', 'verbose_name_plural': 'PR Surveys'},
        ),
        migrations.AlterModelOptions(
            name='prsurveyreview',
            options={'ordering': ['-responded_at'], 'verbose_name': 'PR Survey Review', 'verbose_name_plural': 'PR Survey Reviews'},
        ),
        migrations.AddIndex(
            model_name='aiusagedaily',
            index=models.Index(fields=['date'], name='ai_usage_date_idx'),
        ),
        migrations.AddIndex(
            model_name='aiusagedaily',
            index=models.Index(fields=['member', 'date'], name='ai_usage_member_date_idx'),
        ),
        migrations.AddIndex(
            model_name='aiusagedaily',
            index=models.Index(fields=['source', 'date'], name='ai_usage_source_date_idx'),
        ),
        migrations.AddIndex(
            model_name='prsurvey',
            index=models.Index(fields=['pull_request'], name='pr_survey_pr_idx'),
        ),
        migrations.AddIndex(
            model_name='prsurvey',
            index=models.Index(fields=['author', 'author_ai_assisted'], name='pr_survey_author_ai_idx'),
        ),
        migrations.AddIndex(
            model_name='prsurvey',
            index=models.Index(fields=['author_responded_at'], name='pr_survey_responded_idx'),
        ),
        migrations.AddIndex(
            model_name='prsurveyreview',
            index=models.Index(fields=['survey', 'responded_at'], name='pr_survey_review_survey_idx'),
        ),
        migrations.AddIndex(
            model_name='prsurveyreview',
            index=models.Index(fields=['reviewer', 'responded_at'], name='pr_survey_review_reviewer_idx'),
        ),
        migrations.AddIndex(
            model_name='prsurveyreview',
            index=models.Index(fields=['quality_rating'], name='pr_survey_review_quality_idx'),
        ),
    ]
