# Generated by Django 5.2.8 on 2025-12-10 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0007_alter_aiusagedaily_options_alter_prsurvey_options_and_more'),
        ('teams', '0003_team_billing_details_last_changed_team_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('week_start', models.DateField(help_text='Monday of the week', verbose_name='Week Start')),
                ('prs_merged', models.IntegerField(default=0, verbose_name='PRs Merged')),
                ('avg_cycle_time_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Avg Cycle Time (hours)')),
                ('avg_review_time_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Avg Review Time (hours)')),
                ('commits_count', models.IntegerField(default=0, verbose_name='Commits')),
                ('lines_added', models.IntegerField(default=0, verbose_name='Lines Added')),
                ('lines_removed', models.IntegerField(default=0, verbose_name='Lines Removed')),
                ('revert_count', models.IntegerField(default=0, verbose_name='Reverts')),
                ('hotfix_count', models.IntegerField(default=0, verbose_name='Hotfixes')),
                ('story_points_completed', models.DecimalField(decimal_places=1, default=0, max_digits=10, verbose_name='Story Points')),
                ('issues_resolved', models.IntegerField(default=0, verbose_name='Issues Resolved')),
                ('ai_assisted_prs', models.IntegerField(default=0, verbose_name='AI-Assisted PRs')),
                ('avg_quality_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Avg Quality Rating')),
                ('surveys_completed', models.IntegerField(default=0, verbose_name='Surveys Completed')),
                ('guess_accuracy', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Guess Accuracy (%)')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_metrics', to='metrics.teammember', verbose_name='Team Member')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'verbose_name': 'Weekly Metrics',
                'verbose_name_plural': 'Weekly Metrics',
                'ordering': ['-week_start', 'member'],
                'indexes': [models.Index(fields=['week_start'], name='weekly_metrics_week_idx'), models.Index(fields=['member', 'week_start'], name='weekly_metrics_member_week_idx')],
                'constraints': [models.UniqueConstraint(fields=('team', 'member', 'week_start'), name='unique_team_member_week')],
            },
        ),
    ]
