# Generated by Django 5.2.9 on 2025-12-20 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0007_deployment_deployment_pr_idx_and_more'),
        ('teams', '0003_team_billing_details_last_changed_team_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PRComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('github_comment_id', models.BigIntegerField(help_text='The comment ID from GitHub', verbose_name='GitHub Comment ID')),
                ('body', models.TextField(help_text='The text content of the comment', verbose_name='Comment body')),
                ('comment_type', models.CharField(choices=[('issue', 'Issue Comment'), ('review', 'Review Comment')], help_text='Whether this is an issue comment or review comment', max_length=20, verbose_name='Comment type')),
                ('path', models.CharField(blank=True, help_text='File path for review comments', max_length=500, null=True, verbose_name='File path')),
                ('line', models.IntegerField(blank=True, help_text='Line number for review comments', null=True, verbose_name='Line number')),
                ('in_reply_to_id', models.BigIntegerField(blank=True, help_text='GitHub comment ID this is replying to (for threaded comments)', null=True, verbose_name='In reply to')),
                ('comment_created_at', models.DateTimeField(help_text='When the comment was created on GitHub', verbose_name='Comment created at')),
                ('comment_updated_at', models.DateTimeField(blank=True, help_text='When the comment was last updated on GitHub', null=True, verbose_name='Comment updated at')),
                ('author', models.ForeignKey(help_text='The team member who created the comment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pr_comments', to='metrics.teammember', verbose_name='Author')),
                ('pull_request', models.ForeignKey(help_text='The PR this comment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='metrics.pullrequest', verbose_name='Pull request')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'verbose_name': 'PR Comment',
                'verbose_name_plural': 'PR Comments',
                'ordering': ['-comment_created_at'],
                'indexes': [models.Index(fields=['pull_request', 'comment_created_at'], name='pr_comment_pr_created_idx'), models.Index(fields=['author', 'comment_type'], name='pr_comment_author_type_idx')],
                'constraints': [models.UniqueConstraint(fields=('team', 'github_comment_id'), name='unique_team_pr_comment')],
            },
        ),
    ]
