# Generated by Django 5.2.9 on 2025-12-20 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0008_prcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='pullrequest',
            name='avg_fix_response_hours',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Average time from review to next commit', max_digits=10, null=True, verbose_name='Avg fix response (hours)'),
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='commits_after_first_review',
            field=models.IntegerField(blank=True, help_text='Number of commits made after the first review', null=True, verbose_name='Commits after first review'),
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='review_rounds',
            field=models.IntegerField(blank=True, help_text='Number of review cycles (changes_requested → commits → re-review)', null=True, verbose_name='Review rounds'),
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='total_comments',
            field=models.IntegerField(blank=True, help_text='Total number of comments on this PR', null=True, verbose_name='Total comments'),
        ),
    ]
