# Generated by Django 5.2.8 on 2025-12-10 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0008_weeklymetrics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklymetrics',
            name='ai_assisted_prs',
            field=models.IntegerField(default=0, help_text='Number of PRs created with AI assistance', verbose_name='AI-Assisted PRs'),
        ),
        migrations.AlterField(
            model_name='weeklymetrics',
            name='avg_cycle_time_hours',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Average time from PR creation to merge', max_digits=10, null=True, verbose_name='Avg Cycle Time (hours)'),
        ),
        migrations.AlterField(
            model_name='weeklymetrics',
            name='avg_quality_rating',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Average quality rating from PR surveys', max_digits=3, null=True, verbose_name='Avg Quality Rating'),
        ),
        migrations.AlterField(
            model_name='weeklymetrics',
            name='avg_review_time_hours',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Average time from PR creation to first review', max_digits=10, null=True, verbose_name='Avg Review Time (hours)'),
        ),
        migrations.AlterField(
            model_name='weeklymetrics',
            name='commits_count',
            field=models.IntegerField(default=0, help_text='Number of commits made this week', verbose_name='Commits'),
        ),
        migrations.AlterField(
            model_name='weeklymetrics',
            name='guess_accuracy',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percentage of correct AI usage guesses by reviewers', max_digits=5, null=True, verbose_name='Guess Accuracy (%)'),
        ),
        migrations.AlterField(
            model_name='weeklymetrics',
            name='hotfix_count',
            field=models.IntegerField(default=0, help_text='Number of hotfix PRs this week', verbose_name='Hotfixes'),
        ),
        migrations.AlterField(
            model_name='weeklymetrics',
            name='issues_resolved',
            field=models.IntegerField(default=0, help_text='Number of Jira issues resolved this week', verbose_name='Issues Resolved'),
        ),
        migrations.AlterField(
            model_name='weeklymetrics',
            name='lines_added',
            field=models.IntegerField(default=0, help_text='Total lines added this week', verbose_name='Lines Added'),
        ),
        migrations.AlterField(
            model_name='weeklymetrics',
            name='lines_removed',
            field=models.IntegerField(default=0, help_text='Total lines removed this week', verbose_name='Lines Removed'),
        ),
        migrations.AlterField(
            model_name='weeklymetrics',
            name='member',
            field=models.ForeignKey(help_text='The team member these metrics belong to', on_delete=django.db.models.deletion.CASCADE, related_name='weekly_metrics', to='metrics.teammember', verbose_name='Team Member'),
        ),
        migrations.AlterField(
            model_name='weeklymetrics',
            name='prs_merged',
            field=models.IntegerField(default=0, help_text='Number of PRs merged this week', verbose_name='PRs Merged'),
        ),
        migrations.AlterField(
            model_name='weeklymetrics',
            name='revert_count',
            field=models.IntegerField(default=0, help_text='Number of revert PRs this week', verbose_name='Reverts'),
        ),
        migrations.AlterField(
            model_name='weeklymetrics',
            name='story_points_completed',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Total story points completed this week', max_digits=10, verbose_name='Story Points'),
        ),
        migrations.AlterField(
            model_name='weeklymetrics',
            name='surveys_completed',
            field=models.IntegerField(default=0, help_text='Number of PR surveys completed this week', verbose_name='Surveys Completed'),
        ),
    ]
