# Generated by Django 5.2.9 on 2025-12-20 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0009_add_iteration_fields'),
        ('teams', '0003_team_billing_details_last_changed_team_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewerCorrelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prs_reviewed_together', models.IntegerField(default=0, help_text='Number of PRs where both reviewers submitted reviews', verbose_name='PRs reviewed together')),
                ('agreements', models.IntegerField(default=0, help_text='Number of PRs where both approved or both requested changes', verbose_name='Agreements')),
                ('disagreements', models.IntegerField(default=0, help_text='Number of PRs where one approved and the other requested changes', verbose_name='Disagreements')),
                ('reviewer_1', models.ForeignKey(help_text='First reviewer in the pair', on_delete=django.db.models.deletion.CASCADE, related_name='correlations_as_reviewer_1', to='metrics.teammember', verbose_name='Reviewer 1')),
                ('reviewer_2', models.ForeignKey(help_text='Second reviewer in the pair', on_delete=django.db.models.deletion.CASCADE, related_name='correlations_as_reviewer_2', to='metrics.teammember', verbose_name='Reviewer 2')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'verbose_name': 'Reviewer Correlation',
                'verbose_name_plural': 'Reviewer Correlations',
                'ordering': ['-prs_reviewed_together'],
                'indexes': [models.Index(fields=['reviewer_1', 'reviewer_2'], name='correlation_pair_idx'), models.Index(fields=['prs_reviewed_together'], name='correlation_count_idx')],
                'constraints': [models.UniqueConstraint(fields=('team', 'reviewer_1', 'reviewer_2'), name='unique_team_reviewer_pair')],
            },
        ),
    ]
