# Generated by Django 5.2.8 on 2025-12-10 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0009_alter_weeklymetrics_ai_assisted_prs_and_more'),
        ('teams', '0003_team_billing_details_last_changed_team_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prreview',
            name='github_review_id',
            field=models.BigIntegerField(blank=True, help_text='The review ID from GitHub', null=True, verbose_name='GitHub Review ID'),
        ),
        migrations.AddConstraint(
            model_name='prreview',
            constraint=models.UniqueConstraint(condition=models.Q(('github_review_id__isnull', False)), fields=('team', 'github_review_id'), name='unique_team_review'),
        ),
    ]
