# Generated by Django 5.2.9 on 2025-12-21 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0010_reviewercorrelation'),
        ('teams', '0003_team_billing_details_last_changed_team_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True, help_text='Date this insight was generated for', verbose_name='Date')),
                ('category', models.CharField(choices=[('trend', 'Trend'), ('anomaly', 'Anomaly'), ('comparison', 'Comparison'), ('action', 'Action')], help_text='Type of insight (trend, anomaly, comparison, action)', max_length=20, verbose_name='Category')),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], help_text='Priority level of this insight', max_length=20, verbose_name='Priority')),
                ('title', models.CharField(help_text='Brief title of the insight', max_length=255, verbose_name='Title')),
                ('description', models.TextField(help_text='Detailed description of the insight', verbose_name='Description')),
                ('metric_type', models.CharField(help_text='Type of metric this insight is about (e.g., cycle_time, review_time)', max_length=100, verbose_name='Metric Type')),
                ('metric_value', models.JSONField(blank=True, help_text='JSON data containing metric values and context', null=True, verbose_name='Metric Value')),
                ('comparison_period', models.CharField(blank=True, default='', help_text='Time period for comparison (e.g., week_over_week, month_over_month)', max_length=100, verbose_name='Comparison Period')),
                ('is_dismissed', models.BooleanField(default=False, help_text='Whether this insight has been dismissed by the user', verbose_name='Is Dismissed')),
                ('dismissed_at', models.DateTimeField(blank=True, help_text='When this insight was dismissed', null=True, verbose_name='Dismissed At')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'verbose_name': 'Daily Insight',
                'verbose_name_plural': 'Daily Insights',
                'ordering': ['-date', 'priority', 'category'],
                'indexes': [models.Index(fields=['date', 'category'], name='insight_date_cat_idx'), models.Index(fields=['priority', 'is_dismissed'], name='insight_pri_dismissed_idx')],
            },
        ),
    ]
