# Generated by Django 5.2.8 on 2025-12-11 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0010_prreview_github_review_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pullrequest',
            name='jira_key',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Extracted Jira issue key from PR title or branch (e.g., PROJ-123)', max_length=50, verbose_name='Jira Key'),
        ),
    ]
