# Generated by Django 5.2.9 on 2025-12-21 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0011_add_daily_insight'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='ai_co_authors',
            field=models.JSONField(default=list, help_text='List of AI co-authors detected (e.g., claude, copilot)', verbose_name='AI co-authors'),
        ),
        migrations.AddField(
            model_name='commit',
            name='is_ai_assisted',
            field=models.BooleanField(default=False, help_text='Whether AI co-authors were detected in this commit', verbose_name='AI assisted'),
        ),
        migrations.AddField(
            model_name='prreview',
            name='ai_reviewer_type',
            field=models.CharField(blank=True, help_text='Type of AI reviewer (e.g., coderabbit, copilot)', max_length=50, verbose_name='AI reviewer type'),
        ),
        migrations.AddField(
            model_name='prreview',
            name='body',
            field=models.TextField(blank=True, help_text='The content of the review comment', verbose_name='Review body'),
        ),
        migrations.AddField(
            model_name='prreview',
            name='is_ai_review',
            field=models.BooleanField(default=False, help_text='Whether this review is from an AI bot', verbose_name='AI review'),
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='ai_tools_detected',
            field=models.JSONField(default=list, help_text='List of AI tools detected (e.g., claude_code, copilot)', verbose_name='AI tools detected'),
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='body',
            field=models.TextField(blank=True, help_text='The description/body of the pull request', verbose_name='PR body'),
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='is_ai_assisted',
            field=models.BooleanField(default=False, help_text='Whether AI tools were detected in this PR', verbose_name='AI assisted'),
        ),
    ]
