# Generated by Django 5.2.9 on 2025-12-22 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0012_add_ai_tracking_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='prsurvey',
            name='ai_modification_effort',
            field=models.CharField(blank=True, choices=[('none', 'Used as-is, no changes'), ('minor', 'Minor tweaks only'), ('moderate', 'Significant modifications'), ('major', 'Rewrote most of it'), ('na', "Didn't use AI for code gen")], help_text="How much the author modified AI-generated code (the 'almost right' problem)", max_length=20, null=True, verbose_name='AI Modification Effort'),
        ),
        migrations.AddField(
            model_name='prsurvey',
            name='author_response_source',
            field=models.CharField(blank=True, choices=[('github', 'GitHub'), ('slack', 'Slack'), ('web', 'Web')], help_text='Channel through which the author responded (github, slack, web)', max_length=10, null=True, verbose_name='Author Response Source'),
        ),
        migrations.AddField(
            model_name='prsurveyreview',
            name='response_source',
            field=models.CharField(blank=True, choices=[('github', 'GitHub'), ('slack', 'Slack'), ('web', 'Web')], help_text='Channel through which the reviewer responded (github, slack, web)', max_length=10, null=True, verbose_name='Response Source'),
        ),
        migrations.AlterField(
            model_name='prfile',
            name='file_category',
            field=models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('javascript', 'JavaScript/TypeScript'), ('test', 'Test'), ('docs', 'Documentation'), ('config', 'Configuration'), ('other', 'Other')], help_text='Categorized file type', max_length=50, verbose_name='File category'),
        ),
    ]
