# Generated by Django 5.2.9 on 2025-12-22 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0013_add_survey_response_source_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prsurvey',
            name='author_response_source',
            field=models.CharField(blank=True, choices=[('github', 'GitHub'), ('slack', 'Slack'), ('web', 'Web'), ('auto', 'Auto-detected')], help_text='Channel through which the author responded (github, slack, web)', max_length=10, null=True, verbose_name='Author Response Source'),
        ),
        migrations.AlterField(
            model_name='prsurveyreview',
            name='response_source',
            field=models.CharField(blank=True, choices=[('github', 'GitHub'), ('slack', 'Slack'), ('web', 'Web'), ('auto', 'Auto-detected')], help_text='Channel through which the reviewer responded (github, slack, web)', max_length=10, null=True, verbose_name='Response Source'),
        ),
    ]
