# Generated by Django 5.2.9 on 2025-12-23 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0014_add_auto_response_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prfile',
            name='file_category',
            field=models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('javascript', 'JS/TypeScript'), ('test', 'Test'), ('docs', 'Documentation'), ('config', 'Configuration'), ('other', 'Other')], help_text='Categorized file type', max_length=50, verbose_name='File category'),
        ),
    ]
