# Generated by Django 5.2.9 on 2025-12-23
# Performance optimization: Add composite indexes for common query patterns

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0015_rename_js_typescript_category"),
    ]

    operations = [
        # PullRequest composite indexes for dashboard queries
        migrations.AddIndex(
            model_name="pullrequest",
            index=models.Index(
                fields=["team", "state", "merged_at"],
                name="pr_team_state_merged_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pullrequest",
            index=models.Index(
                fields=["team", "author", "merged_at"],
                name="pr_team_author_merged_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pullrequest",
            index=models.Index(
                fields=["team", "pr_created_at"],
                name="pr_team_created_idx",
            ),
        ),
        # TeamMember composite indexes for sync operations
        migrations.AddIndex(
            model_name="teammember",
            index=models.Index(
                fields=["team", "github_username"],
                name="member_team_gh_username_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="teammember",
            index=models.Index(
                fields=["team", "is_active"],
                name="member_team_active_idx",
            ),
        ),
    ]
