# Generated by Django 5.2.9 on 2025-12-24 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0016_add_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='pullrequest',
            name='assignees',
            field=models.JSONField(blank=True, default=list, help_text='List of assignee usernames from GitHub', verbose_name='Assignees'),
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='is_draft',
            field=models.BooleanField(default=False, help_text='Whether this PR is a draft', verbose_name='Is draft'),
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='labels',
            field=models.JSONField(blank=True, default=list, help_text='List of label names from GitHub', verbose_name='Labels'),
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='linked_issues',
            field=models.JSONField(blank=True, default=list, help_text='List of linked issue numbers from GitHub', verbose_name='Linked issues'),
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='milestone_title',
            field=models.CharField(blank=True, default='', help_text='GitHub milestone title if assigned', max_length=255, verbose_name='Milestone title'),
        ),
    ]
