# Generated by Django 5.2.9 on 2025-12-24 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0017_add_pr_github_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='pullrequest',
            name='ai_detection_version',
            field=models.CharField(blank=True, default='', help_text='Pattern version used for AI detection (e.g., 1.5.0)', max_length=10, verbose_name='AI detection version'),
        ),
    ]
