# Generated by Django 5.2.9 on 2025-12-24 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0018_add_ai_detection_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='pullrequest',
            name='llm_summary',
            field=models.JSONField(blank=True, help_text='AI-generated PR summary with tech detection and description', null=True, verbose_name='LLM summary'),
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='llm_summary_version',
            field=models.CharField(blank=True, default='', help_text='Prompt version used for LLM summary (e.g., 5.0.0)', max_length=10, verbose_name='LLM summary version'),
        ),
    ]
