# Generated by Django 5.2.9 on 2025-12-25 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0020_add_query_optimization_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='pullrequest',
            name='pr_team_repo_idx',
        ),
        migrations.RemoveIndex(
            model_name='pullrequest',
            name='pr_team_ai_assisted_idx',
        ),
        migrations.RemoveIndex(
            model_name='pullrequest',
            name='pr_team_ai_merged_idx',
        ),
    ]
