# Generated by Django migration generator

from django.db import migrations, models


class Migration(migrations.Migration):
    """Add AI signal aggregation fields to PullRequest model.

    These fields aggregate AI signals from related models:
    - has_ai_commits: True if any commit has is_ai_assisted=True or ai_co_authors
    - has_ai_review: True if any PRReview has is_ai_review=True
    - has_ai_files: True if PR modifies AI config files (.cursorrules, CLAUDE.md, etc.)
    """

    dependencies = [
        ("metrics", "0023_seed_dora_benchmarks"),
    ]

    operations = [
        migrations.AddField(
            model_name="pullrequest",
            name="has_ai_commits",
            field=models.BooleanField(
                default=False,
                help_text="True if any commit has AI co-authors or is_ai_assisted",
                verbose_name="Has AI commits",
            ),
        ),
        migrations.AddField(
            model_name="pullrequest",
            name="has_ai_review",
            field=models.BooleanField(
                default=False,
                help_text="True if any review is from an AI reviewer",
                verbose_name="Has AI review",
            ),
        ),
        migrations.AddField(
            model_name="pullrequest",
            name="has_ai_files",
            field=models.BooleanField(
                default=False,
                help_text="True if PR modifies AI config files (.cursorrules, CLAUDE.md, etc.)",
                verbose_name="Has AI config files",
            ),
        ),
    ]
