# Generated by Django 5.2.9 on 2025-12-25 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0026_cleanup_unused_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='pullrequest',
            name='metrics_pr_team_ai_conf_idx',
        ),
    ]
