# Generated by Django 5.2.9 on 2025-12-26 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0027_remove_pullrequest_metrics_pr_team_ai_conf_idx'),
        ('teams', '0003_team_billing_details_last_changed_team_customer_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='aiusagedaily',
            name='ai_usage_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='aiusagedaily',
            name='ai_usage_source_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='commit',
            name='commit_repo_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='prsurvey',
            name='pr_survey_responded_idx',
        ),
        migrations.RemoveIndex(
            model_name='weeklymetrics',
            name='weekly_metrics_week_idx',
        ),
        migrations.AddIndex(
            model_name='prsurvey',
            index=models.Index(fields=['team', 'created_at'], name='pr_survey_team_created_idx'),
        ),
    ]
