# Generated by Django 5.2.9 on 2025-12-28 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0028_drop_unused_indexes_optimize_db'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pullrequest',
            name='is_ai_assisted',
            field=models.BooleanField(blank=True, default=None, help_text='Whether AI tools were detected in this PR (None = not yet processed)', null=True, verbose_name='AI assisted'),
        ),
    ]
