"""Remove duplicate indexes identified in database audit.

Audit findings (2025-12-30):
- commit_pr_idx duplicates metrics_commit_pull_request_id_06f35677 (~7.9 MB each)
- pr_survey_pr_idx duplicates metrics_prsurvey_pull_request_id_key (~4 MB each)
- metrics_aiusagedaily_member_id_0274ee1d covered by ai_usage_member_date_idx (28 MB)
- metrics_commit_author_id_67f38a6f covered by commit_author_date_idx (7.3 MB)
- github_int_org_slug_idx duplicates auto-generated index (16 KB)
- jira_int_cloud_id_idx duplicates auto-generated index (16 KB)

Total savings: ~55 MB
"""

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False  # Required for DROP INDEX CONCURRENTLY

    dependencies = [
        ("metrics", "0029_allow_null_is_ai_assisted"),
        ("integrations", "0001_initial"),
    ]

    operations = [
        # =============================================================
        # metrics_commit: Remove duplicate pull_request_id index
        # Keep: metrics_commit_pull_request_id_06f35677 (auto-generated by Django FK)
        # Drop: commit_pr_idx (manually created, redundant)
        # =============================================================
        migrations.RunSQL(
            sql="DROP INDEX CONCURRENTLY IF EXISTS commit_pr_idx;",
            reverse_sql=(
                "CREATE INDEX CONCURRENTLY commit_pr_idx "
                "ON metrics_commit (pull_request_id);"
            ),
        ),
        # =============================================================
        # metrics_commit: Remove author_id index (covered by composite)
        # Keep: commit_author_date_idx (author_id, committed_at) - more useful
        # Drop: metrics_commit_author_id_67f38a6f (single column, redundant)
        # =============================================================
        migrations.RunSQL(
            sql="DROP INDEX CONCURRENTLY IF EXISTS metrics_commit_author_id_67f38a6f;",
            reverse_sql=(
                "CREATE INDEX CONCURRENTLY metrics_commit_author_id_67f38a6f "
                "ON metrics_commit (author_id);"
            ),
        ),
        # =============================================================
        # metrics_prsurvey: Remove duplicate pull_request_id index
        # Keep: metrics_prsurvey_pull_request_id_key (UNIQUE constraint)
        # Drop: pr_survey_pr_idx (non-unique duplicate)
        # =============================================================
        migrations.RunSQL(
            sql="DROP INDEX CONCURRENTLY IF EXISTS pr_survey_pr_idx;",
            reverse_sql=(
                "CREATE INDEX CONCURRENTLY pr_survey_pr_idx "
                "ON metrics_prsurvey (pull_request_id);"
            ),
        ),
        # =============================================================
        # metrics_aiusagedaily: Remove member_id index (covered by composite)
        # Keep: ai_usage_member_date_idx (member_id, date) - more useful
        # Drop: metrics_aiusagedaily_member_id_0274ee1d (single column)
        # =============================================================
        migrations.RunSQL(
            sql="DROP INDEX CONCURRENTLY IF EXISTS metrics_aiusagedaily_member_id_0274ee1d;",
            reverse_sql=(
                "CREATE INDEX CONCURRENTLY metrics_aiusagedaily_member_id_0274ee1d "
                "ON metrics_aiusagedaily (member_id);"
            ),
        ),
        # =============================================================
        # integrations_githubintegration: Remove duplicate org_slug index
        # Keep: integrations_githubintegration_organization_slug_8d9c65c7 (auto)
        # Drop: github_int_org_slug_idx (manual duplicate)
        # =============================================================
        migrations.RunSQL(
            sql="DROP INDEX CONCURRENTLY IF EXISTS github_int_org_slug_idx;",
            reverse_sql=(
                "CREATE INDEX CONCURRENTLY github_int_org_slug_idx "
                "ON integrations_githubintegration (organization_slug);"
            ),
        ),
        # =============================================================
        # integrations_jiraintegration: Remove duplicate cloud_id index
        # Keep: integrations_jiraintegration_cloud_id_06210669 (auto)
        # Drop: jira_int_cloud_id_idx (manual duplicate)
        # =============================================================
        migrations.RunSQL(
            sql="DROP INDEX CONCURRENTLY IF EXISTS jira_int_cloud_id_idx;",
            reverse_sql=(
                "CREATE INDEX CONCURRENTLY jira_int_cloud_id_idx "
                "ON integrations_jiraintegration (cloud_id);"
            ),
        ),
    ]
