# Generated by Django 5.2.9 on 2025-12-30 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0030_remove_duplicate_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='prsurvey',
            name='pr_survey_pr_idx',
        ),
    ]
