# Generated by Django 5.2.9 on 2025-12-30 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0031_remove_prsurvey_pr_survey_pr_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='commit',
            name='commit_pr_idx',
        ),
    ]
