# Generated by Django 5.2.9 on 2025-12-31 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0032_remove_commit_pr_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyinsight',
            name='category',
            field=models.CharField(choices=[('trend', 'Trend'), ('anomaly', 'Anomaly'), ('comparison', 'Comparison'), ('action', 'Action'), ('llm_insight', 'LLM Insight')], help_text='Type of insight (trend, anomaly, comparison, action)', max_length=20, verbose_name='Category'),
        ),
    ]
