# Generated by Django 5.2.9 on 2025-12-31 15:07
"""
Add GIN indexes to PullRequest model Meta.

Note: These indexes already exist in the database (created via raw SQL in
migration 0020_add_query_optimization_indexes). This migration uses
SeparateDatabaseAndState to record them in Django's migration state without
attempting to recreate them.
"""

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0033_alter_dailyinsight_category"),
        ("teams", "0005_add_pipeline_tracking_fields"),
    ]

    operations = [
        # Use SeparateDatabaseAndState because these indexes already exist
        # from migration 0020 (created via raw SQL). We just need Django
        # to track them in migration state for model-database consistency.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddIndex(
                    model_name="pullrequest",
                    index=django.contrib.postgres.indexes.GinIndex(
                        fields=["ai_tools_detected"],
                        name="pr_llm_ai_tools_gin_idx",
                        opclasses=["jsonb_path_ops"],
                    ),
                ),
                migrations.AddIndex(
                    model_name="pullrequest",
                    index=django.contrib.postgres.indexes.GinIndex(
                        fields=["llm_summary"],
                        name="pr_llm_summary_gin_idx",
                        opclasses=["jsonb_path_ops"],
                    ),
                ),
            ],
            database_operations=[
                # No-op: indexes already exist from migration 0020
            ],
        ),
    ]
