# Generated by Django 5.2.9 on 2026-01-01 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0034_add_gin_indexes_to_model_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='jiraissue',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Full issue description', verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='jiraissue',
            name='labels',
            field=models.JSONField(default=list, help_text='Issue labels as list', verbose_name='Labels'),
        ),
        migrations.AddField(
            model_name='jiraissue',
            name='parent_issue_key',
            field=models.CharField(blank=True, default='', help_text='Parent epic/story key', max_length=50, verbose_name='Parent Issue Key'),
        ),
        migrations.AddField(
            model_name='jiraissue',
            name='priority',
            field=models.CharField(blank=True, default='', help_text='Issue priority (High, Medium, Low)', max_length=50, verbose_name='Priority'),
        ),
    ]
