# Generated by Django 5.2.9 on 2026-01-07 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0035_add_jiraissue_description_labels_priority_parent'),
        ('teams', '0009_add_syncing_members_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CopilotSeatSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(help_text='Date of this snapshot', verbose_name='Date')),
                ('total_seats', models.IntegerField(help_text='Total number of Copilot seats allocated', verbose_name='Total Seats')),
                ('active_this_cycle', models.IntegerField(help_text='Number of seats with activity this billing cycle', verbose_name='Active This Cycle')),
                ('inactive_this_cycle', models.IntegerField(help_text='Number of seats with no activity this billing cycle', verbose_name='Inactive This Cycle')),
                ('pending_cancellation', models.IntegerField(default=0, help_text='Number of seats pending cancellation', verbose_name='Pending Cancellation')),
                ('synced_at', models.DateTimeField(auto_now=True, help_text='When this snapshot was last synced', verbose_name='Synced At')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'verbose_name': 'Copilot Seat Snapshot',
                'verbose_name_plural': 'Copilot Seat Snapshots',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='copilot_seat_date_idx')],
                'constraints': [models.UniqueConstraint(fields=('team', 'date'), name='unique_team_copilot_seat_date')],
            },
        ),
    ]
