# Generated by Django 5.2.9 on 2026-01-07 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0036_add_copilot_seat_snapshot'),
        ('teams', '0009_add_syncing_members_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CopilotLanguageDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('language', models.CharField(max_length=50)),
                ('suggestions_shown', models.IntegerField()),
                ('suggestions_accepted', models.IntegerField()),
                ('lines_suggested', models.IntegerField(default=0)),
                ('lines_accepted', models.IntegerField(default=0)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('team', 'date', 'language'), name='unique_team_copilot_language_date')],
            },
        ),
    ]
