# Generated by Django 5.2.9 on 2026-01-07 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0037_add_copilot_language_daily'),
        ('teams', '0009_add_syncing_members_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CopilotEditorDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('editor', models.CharField(max_length=100)),
                ('suggestions_shown', models.IntegerField()),
                ('suggestions_accepted', models.IntegerField()),
                ('active_users', models.IntegerField(default=0)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='copilotlanguagedaily',
            options={'ordering': ['-date', 'language'], 'verbose_name': 'Copilot Language Daily', 'verbose_name_plural': 'Copilot Language Daily'},
        ),
        migrations.AlterField(
            model_name='copilotlanguagedaily',
            name='date',
            field=models.DateField(help_text='Date of this metrics record', verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='copilotlanguagedaily',
            name='language',
            field=models.CharField(help_text='Programming language name (e.g., Python, TypeScript)', max_length=50, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='copilotlanguagedaily',
            name='lines_accepted',
            field=models.IntegerField(default=0, help_text='Total lines of suggested code accepted', verbose_name='Lines Accepted'),
        ),
        migrations.AlterField(
            model_name='copilotlanguagedaily',
            name='lines_suggested',
            field=models.IntegerField(default=0, help_text='Total lines of code suggested by Copilot', verbose_name='Lines Suggested'),
        ),
        migrations.AlterField(
            model_name='copilotlanguagedaily',
            name='suggestions_accepted',
            field=models.IntegerField(help_text='Number of Copilot suggestions accepted', verbose_name='Suggestions Accepted'),
        ),
        migrations.AlterField(
            model_name='copilotlanguagedaily',
            name='suggestions_shown',
            field=models.IntegerField(help_text='Number of Copilot suggestions shown', verbose_name='Suggestions Shown'),
        ),
        migrations.AlterField(
            model_name='copilotlanguagedaily',
            name='synced_at',
            field=models.DateTimeField(auto_now=True, help_text='When this record was last synced', verbose_name='Synced At'),
        ),
        migrations.AddIndex(
            model_name='copilotlanguagedaily',
            index=models.Index(fields=['date'], name='copilot_lang_date_idx'),
        ),
        migrations.AddField(
            model_name='copiloteditordaily',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team'),
        ),
        migrations.AddConstraint(
            model_name='copiloteditordaily',
            constraint=models.UniqueConstraint(fields=('team', 'date', 'editor'), name='unique_team_copilot_editor_date'),
        ),
    ]
