# Generated by Django 5.2.9 on 2026-01-07 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0038_add_copilot_editor_daily'),
        ('teams', '0009_add_syncing_members_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='copiloteditordaily',
            options={'ordering': ['-date', 'editor'], 'verbose_name': 'Copilot Editor Daily', 'verbose_name_plural': 'Copilot Editor Daily'},
        ),
        migrations.AlterField(
            model_name='copiloteditordaily',
            name='active_users',
            field=models.IntegerField(default=0, help_text='Number of users actively using Copilot in this editor', verbose_name='Active Users'),
        ),
        migrations.AlterField(
            model_name='copiloteditordaily',
            name='date',
            field=models.DateField(help_text='Date of this metrics record', verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='copiloteditordaily',
            name='editor',
            field=models.CharField(help_text='IDE/editor name (e.g., vscode, jetbrains, neovim)', max_length=100, verbose_name='Editor'),
        ),
        migrations.AlterField(
            model_name='copiloteditordaily',
            name='suggestions_accepted',
            field=models.IntegerField(help_text='Number of Copilot suggestions accepted', verbose_name='Suggestions Accepted'),
        ),
        migrations.AlterField(
            model_name='copiloteditordaily',
            name='suggestions_shown',
            field=models.IntegerField(help_text='Number of Copilot suggestions shown', verbose_name='Suggestions Shown'),
        ),
        migrations.AlterField(
            model_name='copiloteditordaily',
            name='synced_at',
            field=models.DateTimeField(auto_now=True, help_text='When this record was last synced', verbose_name='Synced At'),
        ),
        migrations.AddIndex(
            model_name='copiloteditordaily',
            index=models.Index(fields=['date'], name='copilot_editor_date_idx'),
        ),
    ]
