# Generated by Django 5.2.9 on 2026-01-07 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0039_alter_copiloteditordaily_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='copilot_last_activity_at',
            field=models.DateTimeField(blank=True, help_text='When this member last used GitHub Copilot', null=True, verbose_name='Copilot last activity'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='copilot_last_editor',
            field=models.CharField(blank=True, help_text='Editor used for last Copilot activity (e.g., vscode/1.85.1)', max_length=100, null=True, verbose_name='Copilot last editor'),
        ),
    ]
