# Generated by Django 5.2.9 on 2026-01-25 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0041_configure_autovacuum'),
    ]

    operations = [
        migrations.AddField(
            model_name='prsurveyreview',
            name='feedback_clarity',
            field=models.IntegerField(blank=True, choices=[(1, 'Unclear'), (2, 'OK'), (3, 'Clear'), (4, 'Very clear'), (5, 'Excellent')], help_text='How clear/actionable was the review feedback (1=Unclear, 5=Excellent)', null=True, verbose_name='Feedback Clarity'),
        ),
        migrations.AddField(
            model_name='prsurveyreview',
            name='review_burden',
            field=models.IntegerField(blank=True, choices=[(1, 'Very taxing'), (2, 'Taxing'), (3, 'Moderate'), (4, 'Light'), (5, 'Very light')], help_text='How taxing was the review process (1=Very taxing, 5=Very light)', null=True, verbose_name='Review Burden'),
        ),
    ]
