"""
Insight Engine for generating daily insights from team metrics.

The Insight Engine provides:
- InsightResult dataclass for rule outputs
- InsightRule abstract base class
- Rule registry for discovering rules
- compute_insights() function to run all rules
"""

import logging
from abc import ABC, abstractmethod
from dataclasses import dataclass
from datetime import date

from apps.metrics.models import DailyInsight
from apps.teams.models import Team

logger = logging.getLogger(__name__)


@dataclass
class InsightResult:
    """Data structure for an insight generated by a rule."""

    category: str  # trend, anomaly, comparison, action
    priority: str  # high, medium, low
    title: str
    description: str
    metric_type: str
    metric_value: dict | None = None
    comparison_period: str = ""


class InsightRule(ABC):
    """Abstract base class for insight rules.

    Subclasses must implement the evaluate() method to analyze team data
    and return a list of InsightResult instances.
    """

    @abstractmethod
    def evaluate(self, team: Team, target_date: date) -> list[InsightResult]:
        """Evaluate rule and return any insights found.

        Args:
            team: The team to analyze
            target_date: The date to analyze for

        Returns:
            List of InsightResult instances (may be empty if no insights found)
        """
        pass


# Rule registry (module-level)
_rule_registry: list[type[InsightRule]] = []


def register_rule(rule_class: type[InsightRule]) -> None:
    """Add a rule class to the registry.

    Args:
        rule_class: A class that extends InsightRule
    """
    _rule_registry.append(rule_class)


def get_all_rules() -> list[type[InsightRule]]:
    """Return a copy of the rule registry.

    Returns:
        List of registered rule classes
    """
    return _rule_registry.copy()


def clear_rules() -> None:
    """Empty the rule registry.

    Primarily used for testing to ensure a clean state.
    """
    _rule_registry.clear()


def compute_insights(team: Team, target_date: date) -> list[DailyInsight]:
    """Run all registered rules and save insights to database.

    Evaluates each registered rule against the team's data for the target date.
    Creates DailyInsight instances for each InsightResult returned by the rules.
    Handles exceptions gracefully - if a rule fails, it logs the error and continues.

    Args:
        team: The team to generate insights for
        target_date: The date to generate insights for

    Returns:
        List of created DailyInsight instances
    """
    created_insights = []

    for rule_class in _rule_registry:
        try:
            # Instantiate the rule
            rule = rule_class()

            # Call evaluate
            results = rule.evaluate(team, target_date)

            # Save each result as a DailyInsight
            for result in results:
                insight = DailyInsight.objects.create(
                    team=team,
                    date=target_date,
                    category=result.category,
                    priority=result.priority,
                    title=result.title,
                    description=result.description,
                    metric_type=result.metric_type,
                    metric_value=result.metric_value,
                    comparison_period=result.comparison_period,
                )
                created_insights.append(insight)

        except Exception as e:
            # Log the error but continue processing other rules
            logger.exception("Error evaluating rule %s: %s", rule_class.__name__, e)
            continue

    return created_insights
