# Generated by Django 5.2.9 on 2025-12-31 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('metrics', '0032_remove_commit_pr_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PRNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(help_text='The note content (max 2000 characters)', max_length=2000)),
                ('flag', models.CharField(blank=True, choices=[('', 'No Flag'), ('false_positive', 'False Positive'), ('review_later', 'Review Later'), ('important', 'Important'), ('concern', 'Concern')], default='', help_text='Optional category flag for filtering', max_length=20)),
                ('is_resolved', models.BooleanField(default=False, help_text='Whether the note has been marked as resolved')),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When the note was marked as resolved', null=True)),
                ('pull_request', models.ForeignKey(help_text='The PR this note is attached to', on_delete=django.db.models.deletion.CASCADE, related_name='user_notes', to='metrics.pullrequest')),
                ('user', models.ForeignKey(help_text='The user who created this note', on_delete=django.db.models.deletion.CASCADE, related_name='pr_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_resolved', '-created_at'], name='notes_prnot_user_id_6fecc3_idx'), models.Index(fields=['user', 'flag'], name='notes_prnot_user_id_2c051c_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'pull_request'), name='unique_user_pr_note')],
            },
        ),
    ]
