# Generated by Django 5.2.9 on 2025-12-31 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prnote',
            name='content',
            field=models.TextField(blank=True, default='', help_text='Optional note content (max 2000 characters)', max_length=2000),
        ),
    ]
