# Generated by Django 5.1.1 on 2024-10-15 09:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0001_initial"),
        ("djstripe", "0012_2_8"),
        ("waffle", "__latest__"),
    ]

    operations = [
        # See https://github.com/dj-stripe/dj-stripe/issues/2038#issuecomment-2058984705
        migrations.RunSQL(
            "ALTER TABLE djstripe_paymentintent ALTER COLUMN capture_method TYPE varchar(255);"
        ),
        # See https://github.com/django-waffle/django-waffle/issues/317#issuecomment-488398832
        migrations.RunSQL(
            "DROP TABLE IF EXISTS waffle_flag_groups"
        ),
        migrations.RunSQL(
            "DROP TABLE IF EXISTS waffle_flag_users"
        )
    ]
