"""Metrics views package."""

from apps.metrics.views.chart_views import (
    ai_adoption_chart,
    ai_bot_reviews_card,
    ai_detected_metrics_card,
    ai_quality_chart,
    ai_tool_breakdown_chart,
    cicd_pass_rate_card,
    copilot_members_table,
    copilot_metrics_card,
    copilot_trend_chart,
    cycle_time_chart,
    deployment_metrics_card,
    file_category_card,
    iteration_metrics_card,
    key_metrics_cards,
    leaderboard_table,
    pr_size_chart,
    recent_prs_table,
    revert_rate_card,
    review_distribution_chart,
    review_time_chart,
    reviewer_correlations_table,
    reviewer_workload_table,
    survey_ai_detection_card,
    survey_channel_distribution_card,
    survey_response_time_card,
    team_breakdown_table,
    unlinked_prs_table,
)
from apps.metrics.views.dashboard_views import cto_overview, dashboard_redirect, dismiss_insight, home, team_dashboard

__all__ = [
    "ai_adoption_chart",
    "ai_bot_reviews_card",
    "ai_detected_metrics_card",
    "ai_quality_chart",
    "ai_tool_breakdown_chart",
    "cicd_pass_rate_card",
    "copilot_members_table",
    "copilot_metrics_card",
    "copilot_trend_chart",
    "cycle_time_chart",
    "deployment_metrics_card",
    "file_category_card",
    "iteration_metrics_card",
    "key_metrics_cards",
    "team_breakdown_table",
    "leaderboard_table",
    "pr_size_chart",
    "revert_rate_card",
    "review_distribution_chart",
    "review_time_chart",
    "reviewer_correlations_table",
    "reviewer_workload_table",
    "recent_prs_table",
    "unlinked_prs_table",
    "survey_ai_detection_card",
    "survey_channel_distribution_card",
    "survey_response_time_card",
    "home",
    "dashboard_redirect",
    "cto_overview",
    "team_dashboard",
    "dismiss_insight",
]
