# Generated by Django 5.2.8 on 2025-12-10 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='integrationcredential',
            options={'ordering': ['provider'], 'verbose_name': 'Integration Credential', 'verbose_name_plural': 'Integration Credentials'},
        ),
        migrations.AlterField(
            model_name='integrationcredential',
            name='access_token',
            field=models.TextField(help_text='OAuth access token for the integration', verbose_name='Access token'),
        ),
        migrations.AlterField(
            model_name='integrationcredential',
            name='connected_by',
            field=models.ForeignKey(blank=True, help_text='The user who connected this integration', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connected_integrations', to=settings.AUTH_USER_MODEL, verbose_name='Connected by'),
        ),
        migrations.AlterField(
            model_name='integrationcredential',
            name='provider',
            field=models.CharField(choices=[('github', 'GitHub'), ('jira', 'Jira'), ('slack', 'Slack')], db_index=True, help_text='The integration provider (GitHub, Jira, or Slack)', max_length=50, verbose_name='Provider'),
        ),
        migrations.AlterField(
            model_name='integrationcredential',
            name='refresh_token',
            field=models.TextField(blank=True, help_text='OAuth refresh token for renewing access', verbose_name='Refresh token'),
        ),
        migrations.AlterField(
            model_name='integrationcredential',
            name='scopes',
            field=models.JSONField(default=list, help_text='OAuth scopes granted for this integration', verbose_name='Scopes'),
        ),
        migrations.AlterField(
            model_name='integrationcredential',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, help_text='When the access token expires', null=True, verbose_name='Token expires at'),
        ),
    ]
