# Generated by Django 5.2.8 on 2025-12-10 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_alter_integrationcredential_options_and_more'),
        ('teams', '0003_team_billing_details_last_changed_team_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization_slug', models.CharField(help_text='GitHub organization login/slug', max_length=100, verbose_name='Organization slug')),
                ('organization_id', models.BigIntegerField(help_text='GitHub organization ID', verbose_name='Organization ID')),
                ('webhook_secret', models.CharField(help_text='Secret for validating GitHub webhook payloads', max_length=100, verbose_name='Webhook secret')),
                ('last_sync_at', models.DateTimeField(blank=True, help_text='When data was last synced from GitHub', null=True, verbose_name='Last sync at')),
                ('sync_status', models.CharField(choices=[('pending', 'Pending'), ('syncing', 'Syncing'), ('complete', 'Complete'), ('error', 'Error')], default='pending', help_text='Current status of data synchronization', max_length=20, verbose_name='Sync status')),
                ('credential', models.OneToOneField(help_text='OAuth credential for this GitHub integration', on_delete=django.db.models.deletion.CASCADE, related_name='github_integration', to='integrations.integrationcredential', verbose_name='Credential')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'verbose_name': 'GitHub Integration',
                'verbose_name_plural': 'GitHub Integrations',
                'ordering': ['organization_slug'],
            },
        ),
    ]
