# Generated by Django 5.2.8 on 2025-12-10 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_githubintegration'),
        ('teams', '0003_team_billing_details_last_changed_team_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubintegration',
            name='organization_slug',
            field=models.CharField(db_index=True, help_text='GitHub organization login/slug', max_length=100, verbose_name='Organization slug'),
        ),
        migrations.AlterField(
            model_name='githubintegration',
            name='sync_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('syncing', 'Syncing'), ('complete', 'Complete'), ('error', 'Error')], db_index=True, default='pending', help_text='Current status of data synchronization', max_length=20, verbose_name='Sync status'),
        ),
        migrations.AddIndex(
            model_name='githubintegration',
            index=models.Index(fields=['sync_status', 'last_sync_at'], name='github_int_sync_status_idx'),
        ),
        migrations.AddIndex(
            model_name='githubintegration',
            index=models.Index(fields=['organization_slug'], name='github_int_org_slug_idx'),
        ),
    ]
