# Generated by Django 5.2.8 on 2025-12-10 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_alter_githubintegration_organization_slug_and_more'),
        ('teams', '0003_team_billing_details_last_changed_team_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackedRepository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('github_repo_id', models.BigIntegerField(help_text='GitHub repository ID', verbose_name='GitHub repository ID')),
                ('full_name', models.CharField(help_text='Repository full name in owner/repo format', max_length=255, verbose_name='Full name')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this repository is actively being tracked', verbose_name='Is active')),
                ('webhook_id', models.BigIntegerField(blank=True, help_text='GitHub webhook ID for this repository', null=True, verbose_name='Webhook ID')),
                ('last_sync_at', models.DateTimeField(blank=True, help_text='When data was last synced from this repository', null=True, verbose_name='Last sync at')),
                ('integration', models.ForeignKey(help_text='GitHub integration this repository belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='tracked_repositories', to='integrations.githubintegration', verbose_name='Integration')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'verbose_name': 'Tracked Repository',
                'verbose_name_plural': 'Tracked Repositories',
                'ordering': ['full_name'],
                'constraints': [models.UniqueConstraint(fields=('team', 'github_repo_id'), name='unique_team_github_repo')],
            },
        ),
    ]
