# Generated by Django 5.2.8 on 2025-12-10 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0005_trackedrepository'),
        ('teams', '0003_team_billing_details_last_changed_team_customer_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='trackedrepository',
            index=models.Index(fields=['full_name'], name='tracked_repo_name_idx'),
        ),
        migrations.AddIndex(
            model_name='trackedrepository',
            index=models.Index(fields=['github_repo_id'], name='tracked_repo_gh_id_idx'),
        ),
        migrations.AddIndex(
            model_name='trackedrepository',
            index=models.Index(fields=['is_active', 'last_sync_at'], name='tracked_repo_active_sync_idx'),
        ),
        migrations.AddIndex(
            model_name='trackedrepository',
            index=models.Index(fields=['integration', 'is_active'], name='tracked_repo_int_active_idx'),
        ),
    ]
