# Generated by Django 5.2.8 on 2025-12-11 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0006_trackedrepository_tracked_repo_name_idx_and_more'),
        ('teams', '0003_team_billing_details_last_changed_team_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackedrepository',
            name='last_sync_error',
            field=models.TextField(blank=True, help_text='Error message from the last failed sync attempt', null=True, verbose_name='Last sync error'),
        ),
        migrations.AddField(
            model_name='trackedrepository',
            name='sync_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('syncing', 'Syncing'), ('complete', 'Complete'), ('error', 'Error')], db_index=True, default='pending', help_text='Current status of data synchronization', max_length=20, verbose_name='Sync status'),
        ),
        migrations.AddIndex(
            model_name='trackedrepository',
            index=models.Index(fields=['sync_status', 'last_sync_at'], name='tracked_repo_sync_status_idx'),
        ),
    ]
