# Generated by Django 5.2.8 on 2025-12-11 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0007_trackedrepository_last_sync_error_and_more'),
        ('teams', '0003_team_billing_details_last_changed_team_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JiraIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cloud_id', models.CharField(db_index=True, help_text='Atlassian cloud ID', max_length=100, verbose_name='Cloud ID')),
                ('site_name', models.CharField(help_text='Jira site name', max_length=255, verbose_name='Site name')),
                ('site_url', models.URLField(help_text='Jira site URL', verbose_name='Site URL')),
                ('last_sync_at', models.DateTimeField(blank=True, help_text='When data was last synced from Jira', null=True, verbose_name='Last sync at')),
                ('sync_status', models.CharField(choices=[('pending', 'Pending'), ('syncing', 'Syncing'), ('complete', 'Complete'), ('error', 'Error')], db_index=True, default='pending', help_text='Current status of data synchronization', max_length=20, verbose_name='Sync status')),
                ('credential', models.OneToOneField(help_text='OAuth credential for this Jira integration', on_delete=django.db.models.deletion.CASCADE, related_name='jira_integration', to='integrations.integrationcredential', verbose_name='Credential')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'verbose_name': 'Jira Integration',
                'verbose_name_plural': 'Jira Integrations',
                'ordering': ['site_name'],
                'indexes': [models.Index(fields=['sync_status', 'last_sync_at'], name='jira_int_sync_status_idx'), models.Index(fields=['cloud_id'], name='jira_int_cloud_id_idx')],
            },
        ),
    ]
