# Generated by Django 5.2.8 on 2025-12-11 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0008_jiraintegration'),
        ('teams', '0003_team_billing_details_last_changed_team_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackedJiraProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jira_project_id', models.CharField(max_length=50)),
                ('jira_project_key', models.CharField(db_index=True, max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.CharField(choices=[('pending', 'Pending'), ('syncing', 'Syncing'), ('complete', 'Complete'), ('error', 'Error')], db_index=True, default='pending', max_length=20)),
                ('last_sync_error', models.TextField(blank=True, null=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracked_jira_projects', to='integrations.jiraintegration')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'verbose_name': 'Tracked Jira Project',
                'verbose_name_plural': 'Tracked Jira Projects',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['jira_project_key'], name='tracked_jira_proj_key_idx'), models.Index(fields=['sync_status', 'last_sync_at'], name='tracked_jira_sync_idx'), models.Index(fields=['integration', 'is_active'], name='tracked_jira_int_active_idx')],
                'constraints': [models.UniqueConstraint(fields=('team', 'jira_project_id'), name='unique_team_jira_project')],
            },
        ),
    ]
