# Generated by Django 5.2.8 on 2025-12-11 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0009_trackedjiraproject'),
        ('teams', '0003_team_billing_details_last_changed_team_customer_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='trackedjiraproject',
            new_name='tracked_jira_sync_status_idx',
            old_name='tracked_jira_sync_idx',
        ),
        migrations.AlterField(
            model_name='trackedjiraproject',
            name='integration',
            field=models.ForeignKey(help_text='Jira integration this project belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='tracked_jira_projects', to='integrations.jiraintegration', verbose_name='Integration'),
        ),
        migrations.AlterField(
            model_name='trackedjiraproject',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this project is actively being tracked', verbose_name='Is active'),
        ),
        migrations.AlterField(
            model_name='trackedjiraproject',
            name='jira_project_id',
            field=models.CharField(help_text='Jira project ID', max_length=50, verbose_name='Jira project ID'),
        ),
        migrations.AlterField(
            model_name='trackedjiraproject',
            name='jira_project_key',
            field=models.CharField(db_index=True, help_text='Jira project key (e.g., PROJ, ACME)', max_length=20, verbose_name='Project key'),
        ),
        migrations.AlterField(
            model_name='trackedjiraproject',
            name='last_sync_at',
            field=models.DateTimeField(blank=True, help_text='When data was last synced from this project', null=True, verbose_name='Last sync at'),
        ),
        migrations.AlterField(
            model_name='trackedjiraproject',
            name='last_sync_error',
            field=models.TextField(blank=True, help_text='Error message from the last failed sync attempt', null=True, verbose_name='Last sync error'),
        ),
        migrations.AlterField(
            model_name='trackedjiraproject',
            name='name',
            field=models.CharField(help_text='Jira project name', max_length=255, verbose_name='Project name'),
        ),
        migrations.AlterField(
            model_name='trackedjiraproject',
            name='sync_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('syncing', 'Syncing'), ('complete', 'Complete'), ('error', 'Error')], db_index=True, default='pending', help_text='Current status of data synchronization', max_length=20, verbose_name='Sync status'),
        ),
        migrations.AddIndex(
            model_name='trackedjiraproject',
            index=models.Index(fields=['is_active', 'last_sync_at'], name='tracked_jira_active_sync_idx'),
        ),
    ]
