# Generated by Django 5.2.8 on 2025-12-12 12:46

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0010_rename_tracked_jira_sync_idx_tracked_jira_sync_status_idx_and_more'),
        ('teams', '0003_team_billing_details_last_changed_team_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlackIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace_id', models.CharField(db_index=True, help_text='Slack workspace/team ID (e.g., T12345678)', max_length=20, verbose_name='Workspace ID')),
                ('workspace_name', models.CharField(help_text='Slack workspace name', max_length=255, verbose_name='Workspace name')),
                ('bot_user_id', models.CharField(help_text='Slack bot user ID (e.g., U12345678)', max_length=20, verbose_name='Bot user ID')),
                ('leaderboard_channel_id', models.CharField(blank=True, help_text='Slack channel ID for leaderboard posts', max_length=20, verbose_name='Leaderboard channel ID')),
                ('leaderboard_day', models.IntegerField(default=0, help_text='Day of week for leaderboard (0=Monday, 6=Sunday)', verbose_name='Leaderboard day')),
                ('leaderboard_time', models.TimeField(default=datetime.time(9, 0), help_text='Time of day to post leaderboard', verbose_name='Leaderboard time')),
                ('leaderboard_enabled', models.BooleanField(default=True, help_text='Whether weekly leaderboards are enabled', verbose_name='Leaderboard enabled')),
                ('surveys_enabled', models.BooleanField(default=True, help_text='Whether PR surveys are enabled', verbose_name='Surveys enabled')),
                ('reveals_enabled', models.BooleanField(default=True, help_text='Whether AI reveal prompts are enabled', verbose_name='Reveals enabled')),
                ('last_sync_at', models.DateTimeField(blank=True, help_text='When data was last synced from Slack', null=True, verbose_name='Last sync at')),
                ('sync_status', models.CharField(choices=[('pending', 'Pending'), ('syncing', 'Syncing'), ('complete', 'Complete'), ('error', 'Error')], db_index=True, default='pending', help_text='Current status of data synchronization', max_length=20, verbose_name='Sync status')),
                ('credential', models.OneToOneField(help_text='OAuth credential for this Slack integration', on_delete=django.db.models.deletion.CASCADE, related_name='slack_integration', to='integrations.integrationcredential', verbose_name='Credential')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'verbose_name': 'Slack Integration',
                'verbose_name_plural': 'Slack Integrations',
                'ordering': ['workspace_name'],
                'indexes': [models.Index(fields=['sync_status', 'last_sync_at'], name='slack_int_sync_status_idx'), models.Index(fields=['workspace_id'], name='slack_int_workspace_id_idx')],
                'constraints': [models.UniqueConstraint(fields=('team', 'workspace_id'), name='unique_team_workspace')],
            },
        ),
    ]
