# Generated by Django 5.2.8 on 2025-12-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0011_slackintegration'),
    ]

    operations = [
        migrations.AddField(
            model_name='slackintegration',
            name='last_sync_error',
            field=models.TextField(blank=True, help_text='Error message from the last failed sync attempt', null=True, verbose_name='Last sync error'),
        ),
    ]
