# Generated by Django 5.2.9 on 2025-12-13 19:02

import apps.utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0012_slackintegration_last_sync_error'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationcredential',
            name='access_token',
            field=apps.utils.fields.EncryptedTextField(help_text='OAuth access token for the integration (encrypted at rest)', verbose_name='Access token'),
        ),
        migrations.AlterField(
            model_name='integrationcredential',
            name='refresh_token',
            field=apps.utils.fields.EncryptedTextField(blank=True, help_text='OAuth refresh token for renewing access (encrypted at rest)', verbose_name='Refresh token'),
        ),
    ]
