# Generated by Django 5.2.9 on 2025-12-21 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0013_alter_integrationcredential_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackedrepository',
            name='rate_limit_remaining',
            field=models.IntegerField(blank=True, help_text='Remaining API requests for this sync', null=True, verbose_name='Rate limit remaining'),
        ),
        migrations.AddField(
            model_name='trackedrepository',
            name='rate_limit_reset_at',
            field=models.DateTimeField(blank=True, help_text='When rate limit resets', null=True, verbose_name='Rate limit reset at'),
        ),
        migrations.AddField(
            model_name='trackedrepository',
            name='sync_progress',
            field=models.IntegerField(default=0, help_text='Sync progress percentage (0-100)', verbose_name='Sync progress'),
        ),
        migrations.AddField(
            model_name='trackedrepository',
            name='sync_prs_completed',
            field=models.IntegerField(default=0, help_text='PRs synced so far', verbose_name='PRs synced'),
        ),
        migrations.AddField(
            model_name='trackedrepository',
            name='sync_prs_total',
            field=models.IntegerField(blank=True, help_text='Total PRs to sync', null=True, verbose_name='Total PRs to sync'),
        ),
        migrations.AddField(
            model_name='trackedrepository',
            name='sync_started_at',
            field=models.DateTimeField(blank=True, help_text='When sync started', null=True, verbose_name='Sync started at'),
        ),
    ]
