# Generated by Django 5.2.9 on 2025-12-24 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0014_add_rate_limit_and_progress_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackedrepository',
            name='languages',
            field=models.JSONField(default=dict, help_text="Language breakdown from GitHub API (e.g., {'Python': 150000, 'JavaScript': 5000})", verbose_name='Languages'),
        ),
        migrations.AddField(
            model_name='trackedrepository',
            name='languages_updated_at',
            field=models.DateTimeField(blank=True, help_text='When language data was last fetched from GitHub', null=True, verbose_name='Languages updated at'),
        ),
        migrations.AddField(
            model_name='trackedrepository',
            name='primary_language',
            field=models.CharField(blank=True, default='', help_text='Most-used language in this repository', max_length=50, verbose_name='Primary language'),
        ),
    ]
