# Generated by Django 5.2.9 on 2025-12-29 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0015_add_repo_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubintegration',
            name='member_sync_completed_at',
            field=models.DateTimeField(blank=True, help_text='When member sync was completed', null=True, verbose_name='Member sync completed at'),
        ),
        migrations.AddField(
            model_name='githubintegration',
            name='member_sync_error',
            field=models.TextField(blank=True, default='', help_text='Error message from the last failed member sync attempt', verbose_name='Member sync error'),
        ),
        migrations.AddField(
            model_name='githubintegration',
            name='member_sync_result',
            field=models.JSONField(blank=True, help_text='JSON result data from the last member sync (e.g., counts of created/updated members)', null=True, verbose_name='Member sync result'),
        ),
        migrations.AddField(
            model_name='githubintegration',
            name='member_sync_started_at',
            field=models.DateTimeField(blank=True, help_text='When member sync was started', null=True, verbose_name='Member sync started at'),
        ),
        migrations.AddField(
            model_name='githubintegration',
            name='member_sync_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('syncing', 'Syncing'), ('complete', 'Complete'), ('error', 'Error')], default='pending', help_text='Current status of member synchronization from GitHub org', max_length=20, verbose_name='Member sync status'),
        ),
    ]
