# Generated by Django 5.2.9 on 2025-12-31 14:57

import apps.utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0016_githubintegration_member_sync_completed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubintegration',
            name='webhook_secret',
            field=apps.utils.fields.EncryptedTextField(help_text='Secret for validating GitHub webhook payloads (encrypted at rest)', verbose_name='Webhook secret'),
        ),
    ]
