# Generated by Django 5.2.9 on 2026-01-01 21:26

import apps.utils.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0017_encrypt_webhook_secret'),
        ('teams', '0006_add_two_phase_onboarding_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubAppInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('installation_id', models.BigIntegerField(help_text='GitHub App installation ID', unique=True, verbose_name='Installation ID')),
                ('account_type', models.CharField(help_text='Type of GitHub account (Organization or User)', max_length=20, verbose_name='Account type')),
                ('account_login', models.CharField(db_index=True, help_text='GitHub account login/username', max_length=100, verbose_name='Account login')),
                ('account_id', models.BigIntegerField(help_text='GitHub account ID', verbose_name='Account ID')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this installation is active', verbose_name='Is active')),
                ('suspended_at', models.DateTimeField(blank=True, help_text='When the installation was suspended', null=True, verbose_name='Suspended at')),
                ('permissions', models.JSONField(default=dict, help_text='Permissions granted to the GitHub App', verbose_name='Permissions')),
                ('events', models.JSONField(default=list, help_text='Events the GitHub App is subscribed to', verbose_name='Events')),
                ('repository_selection', models.CharField(default='selected', help_text='Repository access selection (all or selected)', max_length=20, verbose_name='Repository selection')),
                ('cached_token', apps.utils.fields.EncryptedTextField(blank=True, help_text='Cached installation access token (encrypted at rest)', verbose_name='Cached token')),
                ('token_expires_at', models.DateTimeField(blank=True, help_text='When the cached token expires', null=True, verbose_name='Token expires at')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'verbose_name': 'GitHub App Installation',
                'verbose_name_plural': 'GitHub App Installations',
                'db_table': 'integrations_github_app_installation',
            },
        ),
    ]
