# Generated by Django 5.2.9 on 2026-01-01 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0018_githubappinstallation'),
        ('teams', '0006_add_two_phase_onboarding_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubappinstallation',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team'),
        ),
    ]
