# Generated by Django 5.2.9 on 2026-01-06 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0019_allow_null_team_github_app_installation'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackedrepository',
            name='app_installation',
            field=models.ForeignKey(blank=True, help_text='GitHub App installation for accessing this repository', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracked_repositories', to='integrations.githubappinstallation', verbose_name='App Installation'),
        ),
    ]
