# Generated by Django 5.2.9 on 2026-01-06 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0020_add_app_installation_to_tracked_repository'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackedrepository',
            name='integration',
            field=models.ForeignKey(blank=True, help_text='GitHub OAuth integration (deprecated, use app_installation)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracked_repositories', to='integrations.githubintegration', verbose_name='Integration'),
        ),
    ]
