# Generated by Django 5.2.9 on 2026-01-07 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0022_create_copilot_feature_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationcredential',
            name='is_revoked',
            field=models.BooleanField(default=False, help_text='Whether the OAuth token has been revoked', verbose_name='Is revoked'),
        ),
        migrations.AddField(
            model_name='integrationcredential',
            name='revocation_reason',
            field=models.CharField(blank=True, default='', help_text='Reason for token revocation (e.g., user revoked in GitHub settings)', max_length=255, verbose_name='Revocation reason'),
        ),
        migrations.AddField(
            model_name='integrationcredential',
            name='revoked_at',
            field=models.DateTimeField(blank=True, help_text='When the token was detected as revoked', null=True, verbose_name='Revoked at'),
        ),
    ]
