"""
Real project configurations for demo data seeding.

Defines target open source projects with their seeding configurations.
Each project will be seeded as a separate team with real GitHub data.

Usage:
    from apps.metrics.seeding.real_projects import REAL_PROJECTS, get_project

    config = get_project("polar")
    print(config.repos)  # ["polarsource/polar", "polarsource/polar-adapters", ...]
"""

from dataclasses import dataclass, field


@dataclass(frozen=True)
class RealProjectConfig:
    """Configuration for a real open source project.

    Attributes:
        repos: List of GitHub repositories in "owner/repo" format.
        team_name: Display name for the team.
        team_slug: URL-safe slug for the team.
        max_prs: Maximum PRs to fetch per repo (default 500).
        max_members: Maximum team members from contributors (default 15).
        days_back: Days of history to fetch (default 90).
        jira_project_key: Synthetic Jira project key (e.g., "POST").
        ai_base_adoption_rate: Base probability of AI usage (0.0-1.0).
        survey_response_rate: Probability of survey completion (0.0-1.0).
        description: Short description of the project.
        industry: Industry category for benchmarking (e.g., "analytics", "crm").
    """

    repos: tuple[str, ...] = field(default_factory=tuple)
    team_name: str = ""
    team_slug: str = ""
    max_prs: int = 500
    max_members: int = 15
    days_back: int = 90
    jira_project_key: str = ""
    ai_base_adoption_rate: float = 0.35
    survey_response_rate: float = 0.60
    description: str = ""
    industry: str = ""  # For industry benchmarking

    @property
    def repo_full_name(self) -> str:
        """Primary repo for backward compatibility."""
        return self.repos[0] if self.repos else ""


# Industry categories for benchmarking
INDUSTRIES = {
    "analytics": "Product Analytics & Observability",
    "ai_llm": "AI & LLM Tools",
    "automation": "Workflow Automation",
    "baas": "Backend-as-a-Service",
    "billing": "Billing & Payments",
    "cms": "Headless CMS",
    "communication": "Communication & Notifications",
    "crm": "CRM & Sales",
    "customer_support": "Customer Support",
    "database": "Database Infrastructure",
    "design": "Design & Creative Tools",
    "devops": "DevOps & Infrastructure",
    "ecommerce": "E-Commerce",
    "feature_flags": "Feature Flags & Experimentation",
    "forms": "Forms & Surveys",
    "identity": "Identity & Security",
    "internal_tools": "Internal Tools & Low-Code",
    "knowledge": "Knowledge Management",
    "project_mgmt": "Project Management",
    "scheduling": "Scheduling & Productivity",
}


# Registry of available real projects
REAL_PROJECTS: dict[str, RealProjectConfig] = {
    # ========== EXISTING 25 PROJECTS (with industry tags) ==========
    "antiwork": RealProjectConfig(
        repos=(
            "antiwork/gumroad",
            "antiwork/flexile",
            "antiwork/helper",
        ),
        team_name="Antiwork",
        team_slug="antiwork-demo",
        max_prs=300,
        max_members=50,
        days_back=90,
        jira_project_key="ANTI",
        ai_base_adoption_rate=0.50,
        survey_response_rate=0.70,
        description="Antiwork portfolio: Gumroad, Flexile, Helper",
        industry="ecommerce",
    ),
    "polar": RealProjectConfig(
        repos=(
            "polarsource/polar",
            "polarsource/polar-adapters",
            "polarsource/polar-python",
            "polarsource/polar-js",
        ),
        team_name="Polar.sh",
        team_slug="polar-demo",
        max_prs=300,
        max_members=50,
        days_back=90,
        jira_project_key="POLAR",
        ai_base_adoption_rate=0.45,
        survey_response_rate=0.60,
        description="Polar platform + SDKs (Python, JS, Adapters)",
        industry="billing",
    ),
    "posthog": RealProjectConfig(
        repos=(
            "PostHog/posthog",
            "PostHog/posthog.com",
            "PostHog/posthog-js",
            "PostHog/posthog-python",
        ),
        team_name="PostHog Analytics",
        team_slug="posthog-demo",
        max_prs=200,
        max_members=50,
        days_back=90,
        jira_project_key="POST",
        ai_base_adoption_rate=0.40,
        survey_response_rate=0.65,
        description="Open-source product analytics + SDKs",
        industry="analytics",
    ),
    "fastapi": RealProjectConfig(
        repos=("tiangolo/fastapi",),
        team_name="FastAPI Team",
        team_slug="fastapi-demo",
        max_prs=300,
        max_members=15,
        days_back=90,
        jira_project_key="FAST",
        ai_base_adoption_rate=0.30,
        survey_response_rate=0.55,
        description="Modern Python web framework",
        industry="devops",
    ),
    "anthropic": RealProjectConfig(
        repos=(
            "anthropics/anthropic-cookbook",
            "anthropics/anthropic-sdk-python",
            "anthropics/courses",
        ),
        team_name="Anthropic",
        team_slug="anthropic-demo",
        max_prs=100,
        max_members=30,
        days_back=90,
        jira_project_key="ANTH",
        ai_base_adoption_rate=0.80,
        survey_response_rate=0.50,
        description="Anthropic AI - cookbook, SDKs, courses",
        industry="ai_llm",
    ),
    "calcom": RealProjectConfig(
        repos=("calcom/cal.com",),
        team_name="Cal.com",
        team_slug="calcom-demo",
        max_prs=150,
        max_members=50,
        days_back=90,
        jira_project_key="CAL",
        ai_base_adoption_rate=0.35,
        survey_response_rate=0.55,
        description="Open source scheduling infrastructure",
        industry="scheduling",
    ),
    "trigger": RealProjectConfig(
        repos=("triggerdotdev/trigger.dev",),
        team_name="Trigger.dev",
        team_slug="trigger-demo",
        max_prs=100,
        max_members=30,
        days_back=90,
        jira_project_key="TRIG",
        ai_base_adoption_rate=0.40,
        survey_response_rate=0.55,
        description="Open source background jobs platform",
        industry="automation",
    ),
    "vercel": RealProjectConfig(
        repos=(
            "vercel/ai",
            "vercel/next.js",
            "vercel/vercel",
        ),
        team_name="Vercel",
        team_slug="vercel-demo",
        max_prs=150,
        max_members=50,
        days_back=90,
        jira_project_key="VERC",
        ai_base_adoption_rate=0.45,
        survey_response_rate=0.55,
        description="Vercel platform, Next.js, and AI SDK",
        industry="devops",
    ),
    "supabase": RealProjectConfig(
        repos=(
            "supabase/supabase",
            "supabase/realtime",
            "supabase/supabase-js",
        ),
        team_name="Supabase",
        team_slug="supabase-demo",
        max_prs=150,
        max_members=50,
        days_back=90,
        jira_project_key="SUPA",
        ai_base_adoption_rate=0.40,
        survey_response_rate=0.55,
        description="Open source Firebase alternative",
        industry="baas",
    ),
    "langchain": RealProjectConfig(
        repos=(
            "langchain-ai/langchain",
            "langchain-ai/langchainjs",
        ),
        team_name="LangChain",
        team_slug="langchain-demo",
        max_prs=200,
        max_members=50,
        days_back=90,
        jira_project_key="LANG",
        ai_base_adoption_rate=0.60,
        survey_response_rate=0.50,
        description="LLM application framework",
        industry="ai_llm",
    ),
    "linear": RealProjectConfig(
        repos=("linearapp/linear",),
        team_name="Linear",
        team_slug="linear-demo",
        max_prs=100,
        max_members=30,
        days_back=90,
        jira_project_key="LIN",
        ai_base_adoption_rate=0.45,
        survey_response_rate=0.60,
        description="Modern issue tracking",
        industry="project_mgmt",
    ),
    "resend": RealProjectConfig(
        repos=(
            "resend/resend-node",
            "resend/react-email",
        ),
        team_name="Resend",
        team_slug="resend-demo",
        max_prs=100,
        max_members=20,
        days_back=90,
        jira_project_key="RSND",
        ai_base_adoption_rate=0.35,
        survey_response_rate=0.55,
        description="Developer-first email API",
        industry="communication",
    ),
    "deno": RealProjectConfig(
        repos=(
            "denoland/deno",
            "denoland/fresh",
        ),
        team_name="Deno",
        team_slug="deno-demo",
        max_prs=150,
        max_members=30,
        days_back=90,
        jira_project_key="DENO",
        ai_base_adoption_rate=0.30,
        survey_response_rate=0.50,
        description="Modern JavaScript/TypeScript runtime",
        industry="devops",
    ),
    "neon": RealProjectConfig(
        repos=(
            "neondatabase/neon",
            "neondatabase/serverless",
        ),
        team_name="Neon",
        team_slug="neon-demo",
        max_prs=100,
        max_members=30,
        days_back=90,
        jira_project_key="NEON",
        ai_base_adoption_rate=0.35,
        survey_response_rate=0.55,
        description="Serverless Postgres",
        industry="database",
    ),
    "twenty": RealProjectConfig(
        repos=("twentyhq/twenty",),
        team_name="Twenty CRM",
        team_slug="twenty-demo",
        max_prs=300,
        max_members=50,
        days_back=90,
        jira_project_key="TWENTY",
        ai_base_adoption_rate=0.45,
        survey_response_rate=0.55,
        description="Open source Salesforce alternative (561 contributors)",
        industry="crm",
    ),
    "novu": RealProjectConfig(
        repos=("novuhq/novu",),
        team_name="Novu",
        team_slug="novu-demo",
        max_prs=300,
        max_members=50,
        days_back=90,
        jira_project_key="NOVU",
        ai_base_adoption_rate=0.50,
        survey_response_rate=0.55,
        description="Notification infrastructure (447 contributors)",
        industry="communication",
    ),
    "hoppscotch": RealProjectConfig(
        repos=("hoppscotch/hoppscotch",),
        team_name="Hoppscotch",
        team_slug="hoppscotch-demo",
        max_prs=200,
        max_members=50,
        days_back=90,
        jira_project_key="HOPP",
        ai_base_adoption_rate=0.40,
        survey_response_rate=0.50,
        description="Open source Postman alternative (314 contributors)",
        industry="devops",
    ),
    "plane": RealProjectConfig(
        repos=("makeplane/plane",),
        team_name="Plane",
        team_slug="plane-demo",
        max_prs=300,
        max_members=50,
        days_back=90,
        jira_project_key="PLANE",
        ai_base_adoption_rate=0.45,
        survey_response_rate=0.55,
        description="Open source Jira/Linear alternative (151 contributors)",
        industry="project_mgmt",
    ),
    "documenso": RealProjectConfig(
        repos=("documenso/documenso",),
        team_name="Documenso",
        team_slug="documenso-demo",
        max_prs=200,
        max_members=50,
        days_back=90,
        jira_project_key="DOCS",
        ai_base_adoption_rate=0.50,
        survey_response_rate=0.55,
        description="Open source DocuSign alternative (142 contributors)",
        industry="scheduling",
    ),
    "coolify": RealProjectConfig(
        repos=("coollabsio/coolify",),
        team_name="Coolify",
        team_slug="coolify-demo",
        max_prs=300,
        max_members=50,
        days_back=90,
        jira_project_key="COOL",
        ai_base_adoption_rate=0.45,
        survey_response_rate=0.55,
        description="Self-hosted Heroku/Vercel alternative (48.7k stars)",
        industry="devops",
    ),
    "infisical": RealProjectConfig(
        repos=("Infisical/infisical",),
        team_name="Infisical",
        team_slug="infisical-demo",
        max_prs=300,
        max_members=50,
        days_back=90,
        jira_project_key="INFI",
        ai_base_adoption_rate=0.45,
        survey_response_rate=0.55,
        description="Secrets management platform (24.3k stars)",
        industry="identity",
    ),
    "dub": RealProjectConfig(
        repos=("dubinc/dub",),
        team_name="Dub",
        team_slug="dub-demo",
        max_prs=300,
        max_members=50,
        days_back=90,
        jira_project_key="DUB",
        ai_base_adoption_rate=0.50,
        survey_response_rate=0.55,
        description="Link management platform (88 contributors)",
        industry="devops",
    ),
    "lago": RealProjectConfig(
        repos=("getlago/lago",),
        team_name="Lago",
        team_slug="lago-demo",
        max_prs=200,
        max_members=30,
        days_back=90,
        jira_project_key="LAGO",
        ai_base_adoption_rate=0.45,
        survey_response_rate=0.55,
        description="Usage-based billing (Y Combinator backed)",
        industry="billing",
    ),
    "formbricks": RealProjectConfig(
        repos=("formbricks/formbricks",),
        team_name="Formbricks",
        team_slug="formbricks-demo",
        max_prs=200,
        max_members=30,
        days_back=90,
        jira_project_key="FORM",
        ai_base_adoption_rate=0.50,
        survey_response_rate=0.60,
        description="Open source Qualtrics alternative",
        industry="forms",
    ),
    "compai": RealProjectConfig(
        repos=("trycompai/comp",),
        team_name="Comp AI",
        team_slug="compai-demo",
        max_prs=200,
        max_members=30,
        days_back=90,
        jira_project_key="COMP",
        ai_base_adoption_rate=0.70,
        survey_response_rate=0.60,
        description="AI-powered compliance platform (SOC2, ISO27001)",
        industry="identity",
    ),
    # ========== PHASE 1: NEW PROJECTS (26-50) ==========
    "chatwoot": RealProjectConfig(
        repos=("chatwoot/chatwoot",),
        team_name="Chatwoot",
        team_slug="chatwoot-demo",
        max_prs=300,
        max_members=50,
        days_back=90,
        jira_project_key="CHAT",
        ai_base_adoption_rate=0.40,
        survey_response_rate=0.55,
        description="Open source Intercom/Zendesk alternative (21k stars)",
        industry="customer_support",
    ),
    "medusa": RealProjectConfig(
        repos=("medusajs/medusa",),
        team_name="Medusa",
        team_slug="medusa-demo",
        max_prs=300,
        max_members=50,
        days_back=90,
        jira_project_key="MED",
        ai_base_adoption_rate=0.45,
        survey_response_rate=0.55,
        description="Open source Shopify alternative (26k stars)",
        industry="ecommerce",
    ),
    "appsmith": RealProjectConfig(
        repos=("appsmithorg/appsmith",),
        team_name="Appsmith",
        team_slug="appsmith-demo",
        max_prs=300,
        max_members=50,
        days_back=90,
        jira_project_key="APP",
        ai_base_adoption_rate=0.50,
        survey_response_rate=0.55,
        description="Open source Retool alternative (35k stars)",
        industry="internal_tools",
    ),
    "n8n": RealProjectConfig(
        repos=("n8n-io/n8n",),
        team_name="n8n",
        team_slug="n8n-demo",
        max_prs=300,
        max_members=50,
        days_back=90,
        jira_project_key="N8N",
        ai_base_adoption_rate=0.55,
        survey_response_rate=0.55,
        description="Open source Zapier alternative (50k stars)",
        industry="automation",
    ),
    "strapi": RealProjectConfig(
        repos=("strapi/strapi",),
        team_name="Strapi",
        team_slug="strapi-demo",
        max_prs=200,
        max_members=50,
        days_back=90,
        jira_project_key="STRA",
        ai_base_adoption_rate=0.40,
        survey_response_rate=0.55,
        description="Leading open source headless CMS (65k stars)",
        industry="cms",
    ),
    "affine": RealProjectConfig(
        repos=("toeverything/AFFiNE",),
        team_name="AFFiNE",
        team_slug="affine-demo",
        max_prs=300,
        max_members=50,
        days_back=90,
        jira_project_key="AFF",
        ai_base_adoption_rate=0.55,
        survey_response_rate=0.55,
        description="Open source Notion alternative (43k stars)",
        industry="knowledge",
    ),
    "dify": RealProjectConfig(
        repos=("langgenius/dify",),
        team_name="Dify",
        team_slug="dify-demo",
        max_prs=300,
        max_members=50,
        days_back=90,
        jira_project_key="DIFY",
        ai_base_adoption_rate=0.70,
        survey_response_rate=0.55,
        description="Open source LLM app platform (58k stars)",
        industry="ai_llm",
    ),
    "pocketbase": RealProjectConfig(
        repos=("pocketbase/pocketbase",),
        team_name="PocketBase",
        team_slug="pocketbase-demo",
        max_prs=200,
        max_members=30,
        days_back=90,
        jira_project_key="PB",
        ai_base_adoption_rate=0.35,
        survey_response_rate=0.55,
        description="Backend in 1 file - Go (42k stars)",
        industry="baas",
    ),
    "plausible": RealProjectConfig(
        repos=("plausible/analytics",),
        team_name="Plausible",
        team_slug="plausible-demo",
        max_prs=200,
        max_members=30,
        days_back=90,
        jira_project_key="PLA",
        ai_base_adoption_rate=0.35,
        survey_response_rate=0.55,
        description="Privacy-first Google Analytics alternative (20k stars)",
        industry="analytics",
    ),
    "signoz": RealProjectConfig(
        repos=("SigNoz/signoz",),
        team_name="SigNoz",
        team_slug="signoz-demo",
        max_prs=300,
        max_members=50,
        days_back=90,
        jira_project_key="SIG",
        ai_base_adoption_rate=0.45,
        survey_response_rate=0.55,
        description="Open source DataDog alternative (19k stars)",
        industry="analytics",
    ),
    "growthbook": RealProjectConfig(
        repos=("growthbook/growthbook",),
        team_name="GrowthBook",
        team_slug="growthbook-demo",
        max_prs=200,
        max_members=30,
        days_back=90,
        jira_project_key="GB",
        ai_base_adoption_rate=0.45,
        survey_response_rate=0.55,
        description="Open source feature flags & A/B testing (6k stars)",
        industry="feature_flags",
    ),
    "huly": RealProjectConfig(
        repos=("hcengineering/huly", "hcengineering/platform"),
        team_name="Huly",
        team_slug="huly-demo",
        max_prs=300,
        max_members=50,
        days_back=90,
        jira_project_key="HULY",
        ai_base_adoption_rate=0.50,
        survey_response_rate=0.55,
        description="All-in-one project management platform (15k stars)",
        industry="project_mgmt",
    ),
    "erxes": RealProjectConfig(
        repos=("erxes/erxes",),
        team_name="Erxes",
        team_slug="erxes-demo",
        max_prs=200,
        max_members=50,
        days_back=90,
        jira_project_key="ERX",
        ai_base_adoption_rate=0.40,
        survey_response_rate=0.55,
        description="Open source HubSpot alternative (3.5k stars)",
        industry="crm",
    ),
    "mattermost": RealProjectConfig(
        repos=("mattermost/mattermost",),
        team_name="Mattermost",
        team_slug="mattermost-demo",
        max_prs=200,
        max_members=50,
        days_back=90,
        jira_project_key="MM",
        ai_base_adoption_rate=0.40,
        survey_response_rate=0.55,
        description="Open source Slack alternative (31k stars)",
        industry="communication",
    ),
    "saleor": RealProjectConfig(
        repos=("saleor/saleor",),
        team_name="Saleor",
        team_slug="saleor-demo",
        max_prs=200,
        max_members=50,
        days_back=90,
        jira_project_key="SAL",
        ai_base_adoption_rate=0.40,
        survey_response_rate=0.55,
        description="GraphQL-first e-commerce platform (21k stars)",
        industry="ecommerce",
    ),
    "tooljet": RealProjectConfig(
        repos=("ToolJet/ToolJet",),
        team_name="ToolJet",
        team_slug="tooljet-demo",
        max_prs=300,
        max_members=50,
        days_back=90,
        jira_project_key="TJ",
        ai_base_adoption_rate=0.50,
        survey_response_rate=0.55,
        description="Open source Retool alternative (32k stars)",
        industry="internal_tools",
    ),
    "directus": RealProjectConfig(
        repos=("directus/directus",),
        team_name="Directus",
        team_slug="directus-demo",
        max_prs=200,
        max_members=50,
        days_back=90,
        jira_project_key="DIR",
        ai_base_adoption_rate=0.40,
        survey_response_rate=0.55,
        description="Open Data Platform / Headless CMS (29k stars)",
        industry="cms",
    ),
    "typebot": RealProjectConfig(
        repos=("baptisteArno/typebot.io",),
        team_name="Typebot",
        team_slug="typebot-demo",
        max_prs=200,
        max_members=30,
        days_back=90,
        jira_project_key="TYPE",
        ai_base_adoption_rate=0.50,
        survey_response_rate=0.55,
        description="Conversational form builder (7k stars)",
        industry="forms",
    ),
    "appwrite": RealProjectConfig(
        repos=("appwrite/appwrite",),
        team_name="Appwrite",
        team_slug="appwrite-demo",
        max_prs=200,
        max_members=50,
        days_back=90,
        jira_project_key="AW",
        ai_base_adoption_rate=0.45,
        survey_response_rate=0.55,
        description="Open source Firebase alternative (46k stars)",
        industry="baas",
    ),
    "ghost": RealProjectConfig(
        repos=("TryGhost/Ghost",),
        team_name="Ghost",
        team_slug="ghost-demo",
        max_prs=200,
        max_members=50,
        days_back=90,
        jira_project_key="GHO",
        ai_base_adoption_rate=0.35,
        survey_response_rate=0.55,
        description="Professional publishing platform (48k stars)",
        industry="cms",
    ),
    "zitadel": RealProjectConfig(
        repos=("zitadel/zitadel",),
        team_name="Zitadel",
        team_slug="zitadel-demo",
        max_prs=200,
        max_members=50,
        days_back=90,
        jira_project_key="ZIT",
        ai_base_adoption_rate=0.40,
        survey_response_rate=0.55,
        description="Identity management platform (9k stars)",
        industry="identity",
    ),
    "flowise": RealProjectConfig(
        repos=("FlowiseAI/Flowise",),
        team_name="Flowise",
        team_slug="flowise-demo",
        max_prs=300,
        max_members=50,
        days_back=90,
        jira_project_key="FLO",
        ai_base_adoption_rate=0.70,
        survey_response_rate=0.55,
        description="Visual LLM chatbot builder (33k stars)",
        industry="ai_llm",
    ),
    "outline": RealProjectConfig(
        repos=("outline/outline",),
        team_name="Outline",
        team_slug="outline-demo",
        max_prs=200,
        max_members=50,
        days_back=90,
        jira_project_key="OUT",
        ai_base_adoption_rate=0.45,
        survey_response_rate=0.55,
        description="Team knowledge base wiki (29k stars)",
        industry="knowledge",
    ),
    "budibase": RealProjectConfig(
        repos=("Budibase/budibase",),
        team_name="Budibase",
        team_slug="budibase-demo",
        max_prs=200,
        max_members=50,
        days_back=90,
        jira_project_key="BUDI",
        ai_base_adoption_rate=0.50,
        survey_response_rate=0.55,
        description="Low-code internal tools platform (23k stars)",
        industry="internal_tools",
    ),
    "webstudio": RealProjectConfig(
        repos=("webstudio-is/webstudio",),
        team_name="Webstudio",
        team_slug="webstudio-demo",
        max_prs=200,
        max_members=30,
        days_back=90,
        jira_project_key="WEB",
        ai_base_adoption_rate=0.45,
        survey_response_rate=0.55,
        description="Open source Webflow alternative (5k stars)",
        industry="design",
    ),
    # ========== PHASE 2: NEW PROJECTS (51-100) ==========
    # --- AI/LLM Tools ---
    "ollama": RealProjectConfig(
        repos=("ollama/ollama",),
        team_name="Ollama",
        team_slug="ollama-demo",
        max_prs=300,
        max_members=50,
        days_back=90,
        jira_project_key="OLL",
        ai_base_adoption_rate=0.65,
        survey_response_rate=0.55,
        description="Run LLMs locally (100k+ stars)",
        industry="ai_llm",
    ),
    "openwebui": RealProjectConfig(
        repos=("open-webui/open-webui",),
        team_name="Open WebUI",
        team_slug="openwebui-demo",
        max_prs=300,
        max_members=50,
        days_back=90,
        jira_project_key="OWU",
        ai_base_adoption_rate=0.70,
        survey_response_rate=0.55,
        description="ChatGPT-style UI for local LLMs (50k+ stars)",
        industry="ai_llm",
    ),
    "lobechat": RealProjectConfig(
        repos=("lobehub/lobe-chat",),
        team_name="LobeChat",
        team_slug="lobechat-demo",
        max_prs=300,
        max_members=50,
        days_back=90,
        jira_project_key="LOBE",
        ai_base_adoption_rate=0.75,
        survey_response_rate=0.55,
        description="Open source ChatGPT/Claude UI (50k+ stars)",
        industry="ai_llm",
    ),
    "continue": RealProjectConfig(
        repos=("continuedev/continue",),
        team_name="Continue",
        team_slug="continue-demo",
        max_prs=300,
        max_members=50,
        days_back=90,
        jira_project_key="CONT",
        ai_base_adoption_rate=0.80,
        survey_response_rate=0.55,
        description="Open source AI code assistant (20k+ stars)",
        industry="ai_llm",
    ),
    "jan": RealProjectConfig(
        repos=("janhq/jan",),
        team_name="Jan",
        team_slug="jan-demo",
        max_prs=300,
        max_members=50,
        days_back=90,
        jira_project_key="JAN",
        ai_base_adoption_rate=0.70,
        survey_response_rate=0.55,
        description="Open source ChatGPT alternative runs offline (25k+ stars)",
        industry="ai_llm",
    ),
    # --- DevOps/Infrastructure ---
    "portainer": RealProjectConfig(
        repos=("portainer/portainer",),
        team_name="Portainer",
        team_slug="portainer-demo",
        max_prs=200,
        max_members=50,
        days_back=90,
        jira_project_key="PORT",
        ai_base_adoption_rate=0.35,
        survey_response_rate=0.55,
        description="Container management platform (31k+ stars)",
        industry="devops",
    ),
    "netdata": RealProjectConfig(
        repos=("netdata/netdata",),
        team_name="Netdata",
        team_slug="netdata-demo",
        max_prs=200,
        max_members=50,
        days_back=90,
        jira_project_key="NETD",
        ai_base_adoption_rate=0.40,
        survey_response_rate=0.55,
        description="Real-time infrastructure monitoring (72k+ stars)",
        industry="analytics",
    ),
    "grafana": RealProjectConfig(
        repos=("grafana/grafana",),
        team_name="Grafana",
        team_slug="grafana-demo",
        max_prs=200,
        max_members=50,
        days_back=90,
        jira_project_key="GRAF",
        ai_base_adoption_rate=0.40,
        survey_response_rate=0.55,
        description="Observability platform (65k+ stars)",
        industry="analytics",
    ),
    "traefik": RealProjectConfig(
        repos=("traefik/traefik",),
        team_name="Traefik",
        team_slug="traefik-demo",
        max_prs=200,
        max_members=50,
        days_back=90,
        jira_project_key="TRAE",
        ai_base_adoption_rate=0.35,
        survey_response_rate=0.55,
        description="Cloud native application proxy (52k+ stars)",
        industry="devops",
    ),
    # --- E-commerce ---
    "spree": RealProjectConfig(
        repos=("spree/spree",),
        team_name="Spree Commerce",
        team_slug="spree-demo",
        max_prs=200,
        max_members=50,
        days_back=90,
        jira_project_key="SPREE",
        ai_base_adoption_rate=0.35,
        survey_response_rate=0.55,
        description="Open source e-commerce platform (13k+ stars)",
        industry="ecommerce",
    ),
    "bagisto": RealProjectConfig(
        repos=("bagisto/bagisto",),
        team_name="Bagisto",
        team_slug="bagisto-demo",
        max_prs=200,
        max_members=50,
        days_back=90,
        jira_project_key="BAG",
        ai_base_adoption_rate=0.40,
        survey_response_rate=0.55,
        description="Laravel e-commerce platform (16k+ stars)",
        industry="ecommerce",
    ),
    # --- CMS ---
    "payload": RealProjectConfig(
        repos=("payloadcms/payload",),
        team_name="Payload CMS",
        team_slug="payload-demo",
        max_prs=300,
        max_members=50,
        days_back=90,
        jira_project_key="PAYL",
        ai_base_adoption_rate=0.50,
        survey_response_rate=0.55,
        description="Headless CMS & App Framework (30k+ stars)",
        industry="cms",
    ),
    "keystone": RealProjectConfig(
        repos=("keystonejs/keystone",),
        team_name="Keystone",
        team_slug="keystone-demo",
        max_prs=200,
        max_members=50,
        days_back=90,
        jira_project_key="KEYS",
        ai_base_adoption_rate=0.40,
        survey_response_rate=0.55,
        description="Headless CMS & GraphQL API (9k+ stars)",
        industry="cms",
    ),
    # --- Communication ---
    "rocketchat": RealProjectConfig(
        repos=("RocketChat/Rocket.Chat",),
        team_name="Rocket.Chat",
        team_slug="rocketchat-demo",
        max_prs=200,
        max_members=50,
        days_back=90,
        jira_project_key="ROCK",
        ai_base_adoption_rate=0.40,
        survey_response_rate=0.55,
        description="Open source Slack alternative (41k+ stars)",
        industry="communication",
    ),
    "zulip": RealProjectConfig(
        repos=("zulip/zulip",),
        team_name="Zulip",
        team_slug="zulip-demo",
        max_prs=200,
        max_members=50,
        days_back=90,
        jira_project_key="ZUL",
        ai_base_adoption_rate=0.35,
        survey_response_rate=0.55,
        description="Organized team chat (22k+ stars)",
        industry="communication",
    ),
    # --- Knowledge Management ---
    "appflowy": RealProjectConfig(
        repos=("AppFlowy-IO/AppFlowy",),
        team_name="AppFlowy",
        team_slug="appflowy-demo",
        max_prs=300,
        max_members=50,
        days_back=90,
        jira_project_key="APPF",
        ai_base_adoption_rate=0.55,
        survey_response_rate=0.55,
        description="Open source Notion alternative (60k+ stars)",
        industry="knowledge",
    ),
    "logseq": RealProjectConfig(
        repos=("logseq/logseq",),
        team_name="Logseq",
        team_slug="logseq-demo",
        max_prs=200,
        max_members=50,
        days_back=90,
        jira_project_key="LOGS",
        ai_base_adoption_rate=0.45,
        survey_response_rate=0.55,
        description="Privacy-first knowledge base (35k+ stars)",
        industry="knowledge",
    ),
    "silverbullet": RealProjectConfig(
        repos=("silverbulletmd/silverbullet",),
        team_name="SilverBullet",
        team_slug="silverbullet-demo",
        max_prs=200,
        max_members=30,
        days_back=90,
        jira_project_key="SILV",
        ai_base_adoption_rate=0.45,
        survey_response_rate=0.55,
        description="Note-taking with Markdown (4k+ stars)",
        industry="knowledge",
    ),
    # --- Internal Tools ---
    "nocodb": RealProjectConfig(
        repos=("nocodb/nocodb",),
        team_name="NocoDB",
        team_slug="nocodb-demo",
        max_prs=300,
        max_members=50,
        days_back=90,
        jira_project_key="NOCO",
        ai_base_adoption_rate=0.50,
        survey_response_rate=0.55,
        description="Open source Airtable alternative (50k+ stars)",
        industry="internal_tools",
    ),
    "baserow": RealProjectConfig(
        repos=("baserow/baserow",),
        team_name="Baserow",
        team_slug="baserow-demo",
        max_prs=200,
        max_members=50,
        days_back=90,
        jira_project_key="BROW",
        ai_base_adoption_rate=0.45,
        survey_response_rate=0.55,
        description="Open source Airtable alternative (13k+ stars)",
        industry="internal_tools",
    ),
    "illa": RealProjectConfig(
        repos=("illacloud/illa-builder",),
        team_name="ILLA Builder",
        team_slug="illa-demo",
        max_prs=200,
        max_members=50,
        days_back=90,
        jira_project_key="ILLA",
        ai_base_adoption_rate=0.55,
        survey_response_rate=0.55,
        description="Low-code platform with AI (12k+ stars)",
        industry="internal_tools",
    ),
    # --- Identity/Security ---
    "keycloak": RealProjectConfig(
        repos=("keycloak/keycloak",),
        team_name="Keycloak",
        team_slug="keycloak-demo",
        max_prs=200,
        max_members=50,
        days_back=90,
        jira_project_key="KEYC",
        ai_base_adoption_rate=0.35,
        survey_response_rate=0.55,
        description="Open source IAM (24k+ stars)",
        industry="identity",
    ),
    "casdoor": RealProjectConfig(
        repos=("casdoor/casdoor",),
        team_name="Casdoor",
        team_slug="casdoor-demo",
        max_prs=200,
        max_members=50,
        days_back=90,
        jira_project_key="CASD",
        ai_base_adoption_rate=0.40,
        survey_response_rate=0.55,
        description="Identity/SSO platform (10k+ stars)",
        industry="identity",
    ),
    # --- Database ---
    "surrealdb": RealProjectConfig(
        repos=("surrealdb/surrealdb",),
        team_name="SurrealDB",
        team_slug="surrealdb-demo",
        max_prs=200,
        max_members=50,
        days_back=90,
        jira_project_key="SURR",
        ai_base_adoption_rate=0.45,
        survey_response_rate=0.55,
        description="Multi-model database (28k+ stars)",
        industry="database",
    ),
    "questdb": RealProjectConfig(
        repos=("questdb/questdb",),
        team_name="QuestDB",
        team_slug="questdb-demo",
        max_prs=200,
        max_members=50,
        days_back=90,
        jira_project_key="QUST",
        ai_base_adoption_rate=0.40,
        survey_response_rate=0.55,
        description="Time-series database (15k+ stars)",
        industry="database",
    ),
    # --- Analytics ---
    "umami": RealProjectConfig(
        repos=("umami-software/umami",),
        team_name="Umami",
        team_slug="umami-demo",
        max_prs=200,
        max_members=50,
        days_back=90,
        jira_project_key="UMA",
        ai_base_adoption_rate=0.40,
        survey_response_rate=0.55,
        description="Privacy-focused analytics (24k+ stars)",
        industry="analytics",
    ),
    "openreplay": RealProjectConfig(
        repos=("openreplay/openreplay",),
        team_name="OpenReplay",
        team_slug="openreplay-demo",
        max_prs=200,
        max_members=50,
        days_back=90,
        jira_project_key="OREP",
        ai_base_adoption_rate=0.45,
        survey_response_rate=0.55,
        description="Session replay platform (10k+ stars)",
        industry="analytics",
    ),
    "matomo": RealProjectConfig(
        repos=("matomo-org/matomo",),
        team_name="Matomo",
        team_slug="matomo-demo",
        max_prs=200,
        max_members=50,
        days_back=90,
        jira_project_key="MAT",
        ai_base_adoption_rate=0.35,
        survey_response_rate=0.55,
        description="Google Analytics alternative (20k+ stars)",
        industry="analytics",
    ),
    # --- Billing ---
    "hyperswitch": RealProjectConfig(
        repos=("juspay/hyperswitch",),
        team_name="Hyperswitch",
        team_slug="hyperswitch-demo",
        max_prs=300,
        max_members=50,
        days_back=90,
        jira_project_key="HYPR",
        ai_base_adoption_rate=0.45,
        survey_response_rate=0.55,
        description="Open source payment switch (13k+ stars)",
        industry="billing",
    ),
    "killbill": RealProjectConfig(
        repos=("killbill/killbill",),
        team_name="Kill Bill",
        team_slug="killbill-demo",
        max_prs=200,
        max_members=30,
        days_back=90,
        jira_project_key="KILL",
        ai_base_adoption_rate=0.30,
        survey_response_rate=0.55,
        description="Subscription billing platform (4k+ stars)",
        industry="billing",
    ),
    # --- Design ---
    "penpot": RealProjectConfig(
        repos=("penpot/penpot",),
        team_name="Penpot",
        team_slug="penpot-demo",
        max_prs=200,
        max_members=50,
        days_back=90,
        jira_project_key="PENP",
        ai_base_adoption_rate=0.40,
        survey_response_rate=0.55,
        description="Open source Figma alternative (35k+ stars)",
        industry="design",
    ),
    "excalidraw": RealProjectConfig(
        repos=("excalidraw/excalidraw",),
        team_name="Excalidraw",
        team_slug="excalidraw-demo",
        max_prs=200,
        max_members=50,
        days_back=90,
        jira_project_key="EXCA",
        ai_base_adoption_rate=0.45,
        survey_response_rate=0.55,
        description="Virtual whiteboard (90k+ stars)",
        industry="design",
    ),
    # --- Automation ---
    "activepieces": RealProjectConfig(
        repos=("activepieces/activepieces",),
        team_name="Activepieces",
        team_slug="activepieces-demo",
        max_prs=300,
        max_members=50,
        days_back=90,
        jira_project_key="ACTP",
        ai_base_adoption_rate=0.55,
        survey_response_rate=0.55,
        description="Open source Zapier alternative (11k+ stars)",
        industry="automation",
    ),
    "automatisch": RealProjectConfig(
        repos=("automatisch/automatisch",),
        team_name="Automatisch",
        team_slug="automatisch-demo",
        max_prs=200,
        max_members=30,
        days_back=90,
        jira_project_key="AUTM",
        ai_base_adoption_rate=0.45,
        survey_response_rate=0.55,
        description="Business automation tool (6k+ stars)",
        industry="automation",
    ),
    "windmill": RealProjectConfig(
        repos=("windmill-labs/windmill",),
        team_name="Windmill",
        team_slug="windmill-demo",
        max_prs=300,
        max_members=50,
        days_back=90,
        jira_project_key="WNDM",
        ai_base_adoption_rate=0.50,
        survey_response_rate=0.55,
        description="Developer platform for scripts/workflows (11k+ stars)",
        industry="automation",
    ),
    # --- Backend/BaaS ---
    "hasura": RealProjectConfig(
        repos=("hasura/graphql-engine",),
        team_name="Hasura",
        team_slug="hasura-demo",
        max_prs=200,
        max_members=50,
        days_back=90,
        jira_project_key="HASU",
        ai_base_adoption_rate=0.40,
        survey_response_rate=0.55,
        description="Instant GraphQL APIs (31k+ stars)",
        industry="baas",
    ),
    "parse": RealProjectConfig(
        repos=("parse-community/parse-server",),
        team_name="Parse Server",
        team_slug="parse-demo",
        max_prs=200,
        max_members=50,
        days_back=90,
        jira_project_key="PARS",
        ai_base_adoption_rate=0.30,
        survey_response_rate=0.55,
        description="Open source backend (21k+ stars)",
        industry="baas",
    ),
    # --- Popular Frameworks ---
    "laravel": RealProjectConfig(
        repos=("laravel/framework", "laravel/laravel"),
        team_name="Laravel",
        team_slug="laravel-demo",
        max_prs=200,
        max_members=50,
        days_back=90,
        jira_project_key="LARA",
        ai_base_adoption_rate=0.40,
        survey_response_rate=0.55,
        description="PHP web framework (80k+ stars)",
        industry="devops",
    ),
    "remix": RealProjectConfig(
        repos=("remix-run/remix",),
        team_name="Remix",
        team_slug="remix-demo",
        max_prs=200,
        max_members=50,
        days_back=90,
        jira_project_key="REMX",
        ai_base_adoption_rate=0.45,
        survey_response_rate=0.55,
        description="React framework for web standards (30k+ stars)",
        industry="devops",
    ),
    "astro": RealProjectConfig(
        repos=("withastro/astro",),
        team_name="Astro",
        team_slug="astro-demo",
        max_prs=200,
        max_members=50,
        days_back=90,
        jira_project_key="ASTR",
        ai_base_adoption_rate=0.50,
        survey_response_rate=0.55,
        description="Content-focused web framework (48k+ stars)",
        industry="devops",
    ),
    "nuxt": RealProjectConfig(
        repos=("nuxt/nuxt",),
        team_name="Nuxt",
        team_slug="nuxt-demo",
        max_prs=200,
        max_members=50,
        days_back=90,
        jira_project_key="NUXT",
        ai_base_adoption_rate=0.45,
        survey_response_rate=0.55,
        description="Vue framework for web apps (55k+ stars)",
        industry="devops",
    ),
    "svelte": RealProjectConfig(
        repos=("sveltejs/svelte", "sveltejs/kit"),
        team_name="Svelte",
        team_slug="svelte-demo",
        max_prs=200,
        max_members=50,
        days_back=90,
        jira_project_key="SVEL",
        ai_base_adoption_rate=0.45,
        survey_response_rate=0.55,
        description="Cybernetically enhanced web apps (80k+ stars)",
        industry="devops",
    ),
    # --- Feature Flags ---
    "flagsmith": RealProjectConfig(
        repos=("Flagsmith/flagsmith",),
        team_name="Flagsmith",
        team_slug="flagsmith-demo",
        max_prs=200,
        max_members=50,
        days_back=90,
        jira_project_key="FGSM",
        ai_base_adoption_rate=0.45,
        survey_response_rate=0.55,
        description="Feature flag & remote config (5k+ stars)",
        industry="feature_flags",
    ),
    "unleash": RealProjectConfig(
        repos=("Unleash/unleash",),
        team_name="Unleash",
        team_slug="unleash-demo",
        max_prs=200,
        max_members=50,
        days_back=90,
        jira_project_key="UNLE",
        ai_base_adoption_rate=0.40,
        survey_response_rate=0.55,
        description="Open source feature management (11k+ stars)",
        industry="feature_flags",
    ),
    # --- Forms ---
    "heyform": RealProjectConfig(
        repos=("heyform/heyform",),
        team_name="HeyForm",
        team_slug="heyform-demo",
        max_prs=200,
        max_members=30,
        days_back=90,
        jira_project_key="HEYF",
        ai_base_adoption_rate=0.45,
        survey_response_rate=0.55,
        description="Open source Typeform alternative (7k+ stars)",
        industry="forms",
    ),
    # --- Customer Support ---
    "papercups": RealProjectConfig(
        repos=("papercups-io/papercups",),
        team_name="Papercups",
        team_slug="papercups-demo",
        max_prs=200,
        max_members=30,
        days_back=90,
        jira_project_key="PAPR",
        ai_base_adoption_rate=0.35,
        survey_response_rate=0.55,
        description="Open source Intercom alternative (6k+ stars)",
        industry="customer_support",
    ),
    # --- Project Management ---
    "focalboard": RealProjectConfig(
        repos=("mattermost-community/focalboard",),
        team_name="Focalboard",
        team_slug="focalboard-demo",
        max_prs=200,
        max_members=50,
        days_back=90,
        jira_project_key="FOCL",
        ai_base_adoption_rate=0.40,
        survey_response_rate=0.55,
        description="Open source Trello/Notion alternative (22k+ stars)",
        industry="project_mgmt",
    ),
    "taiga": RealProjectConfig(
        repos=("taigaio/taiga-back", "taigaio/taiga-front"),
        team_name="Taiga",
        team_slug="taiga-demo",
        max_prs=200,
        max_members=50,
        days_back=90,
        jira_project_key="TAIG",
        ai_base_adoption_rate=0.35,
        survey_response_rate=0.55,
        description="Agile project management (4k+ stars)",
        industry="project_mgmt",
    ),
    # --- Scheduling ---
    "rallly": RealProjectConfig(
        repos=("lukevella/rallly",),
        team_name="Rallly",
        team_slug="rallly-demo",
        max_prs=200,
        max_members=30,
        days_back=90,
        jira_project_key="RALL",
        ai_base_adoption_rate=0.45,
        survey_response_rate=0.55,
        description="Open source Doodle alternative (4k+ stars)",
        industry="scheduling",
    ),
    # --- CRM ---
    "erpnext": RealProjectConfig(
        repos=("frappe/erpnext",),
        team_name="ERPNext",
        team_slug="erpnext-demo",
        max_prs=200,
        max_members=50,
        days_back=90,
        jira_project_key="ERPN",
        ai_base_adoption_rate=0.35,
        survey_response_rate=0.55,
        description="Open source ERP (20k+ stars)",
        industry="crm",
    ),
}


def get_project(name: str) -> RealProjectConfig:
    """Get project configuration by name.

    Args:
        name: Project name (e.g., "posthog", "polar", "fastapi").

    Returns:
        RealProjectConfig for the project.

    Raises:
        KeyError: If project name is not found.
    """
    if name not in REAL_PROJECTS:
        available = ", ".join(REAL_PROJECTS.keys())
        raise KeyError(f"Project '{name}' not found. Available: {available}")
    return REAL_PROJECTS[name]


def list_projects() -> list[str]:
    """List all available project names.

    Returns:
        List of project names.
    """
    return list(REAL_PROJECTS.keys())


def get_all_projects() -> list[RealProjectConfig]:
    """Get all project configurations.

    Returns:
        List of all RealProjectConfig objects.
    """
    return list(REAL_PROJECTS.values())


def get_projects_by_industry(industry: str) -> list[RealProjectConfig]:
    """Get all projects in a specific industry.

    Args:
        industry: Industry key (e.g., "analytics", "crm").

    Returns:
        List of projects in that industry.
    """
    return [p for p in REAL_PROJECTS.values() if p.industry == industry]


def list_industries() -> dict[str, int]:
    """List all industries with project counts.

    Returns:
        Dictionary mapping industry key to project count.
    """
    counts: dict[str, int] = {}
    for project in REAL_PROJECTS.values():
        if project.industry:
            counts[project.industry] = counts.get(project.industry, 0) + 1
    return counts


def get_industry_display_name(industry: str) -> str:
    """Get display name for an industry.

    Args:
        industry: Industry key (e.g., "analytics").

    Returns:
        Human-readable display name.
    """
    return INDUSTRIES.get(industry, industry.replace("_", " ").title())
