# Generated by Django 5.2.9 on 2026-02-15 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0012_add_copilot_price_tier'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicRepoRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('github_url', models.URLField(help_text='GitHub repository URL')),
                ('email', models.EmailField(help_text='Contact email', max_length=254)),
                ('role', models.CharField(choices=[('maintainer', 'Maintainer'), ('contributor', 'Contributor'), ('fan', 'Fan')], help_text="Requester's relationship to the project", max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Review status', max_length=20)),
            ],
            options={
                'verbose_name': 'Public Repo Request',
                'verbose_name_plural': 'Public Repo Requests',
            },
        ),
        migrations.CreateModel(
            name='PublicOrgProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_slug', models.SlugField(help_text="Clean URL slug (e.g., 'posthog' not 'posthog-demo')", max_length=100, unique=True)),
                ('industry', models.CharField(choices=[('analytics', 'Product Analytics & Observability'), ('ai_llm', 'AI & LLM Tools'), ('automation', 'Workflow Automation'), ('baas', 'Backend-as-a-Service'), ('billing', 'Billing & Payments'), ('cms', 'Headless CMS'), ('communication', 'Communication & Notifications'), ('crm', 'CRM & Sales'), ('customer_support', 'Customer Support'), ('database', 'Database Infrastructure'), ('design', 'Design & Creative Tools'), ('devops', 'DevOps & Infrastructure'), ('ecommerce', 'E-Commerce'), ('feature_flags', 'Feature Flags & Experimentation'), ('forms', 'Forms & Surveys'), ('identity', 'Identity & Security'), ('internal_tools', 'Internal Tools & Low-Code'), ('knowledge', 'Knowledge Management'), ('project_mgmt', 'Project Management'), ('scheduling', 'Scheduling & Productivity')], help_text='Industry category for benchmarking', max_length=50)),
                ('description', models.TextField(blank=True, default='', help_text='Short description from GitHub org')),
                ('github_org_url', models.URLField(blank=True, default='', help_text='GitHub organization URL')),
                ('logo_url', models.URLField(blank=True, default='', help_text='Organization logo URL')),
                ('is_public', models.BooleanField(db_index=True, default=False, help_text='Whether this org appears on public pages')),
                ('display_name', models.CharField(help_text='Clean organization name for display', max_length=200)),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='public_profile', to='teams.team')),
            ],
            options={
                'verbose_name': 'Public Org Profile',
                'verbose_name_plural': 'Public Org Profiles',
            },
        ),
        migrations.CreateModel(
            name='PublicOrgStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_prs', models.IntegerField(default=0, help_text='Total merged PRs analyzed')),
                ('ai_assisted_pct', models.DecimalField(decimal_places=2, default=0, help_text='Percentage of PRs that are AI-assisted', max_digits=5)),
                ('median_cycle_time_hours', models.DecimalField(decimal_places=2, default=0, help_text='Median cycle time in hours', max_digits=10)),
                ('median_review_time_hours', models.DecimalField(decimal_places=2, default=0, help_text='Median review time in hours', max_digits=10)),
                ('active_contributors_90d', models.IntegerField(default=0, help_text='Unique PR authors in last 90 days')),
                ('top_ai_tools', models.JSONField(blank=True, default=list, help_text='List of {tool, count, pct} dicts')),
                ('last_computed_at', models.DateTimeField(blank=True, help_text='When stats were last computed', null=True)),
                ('org_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='public.publicorgprofile')),
            ],
            options={
                'verbose_name': 'Public Org Stats',
                'verbose_name_plural': 'Public Org Stats',
            },
        ),
    ]
