# Generated by Django 5.2.9 on 2026-03-14 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_populate_public_org_profiles'),
        ('teams', '0012_add_copilot_price_tier'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicRepoProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('github_repo', models.CharField(help_text='Full owner/repo format matching PullRequest.github_repo', max_length=200)),
                ('repo_slug', models.SlugField(help_text="URL slug for the repo (e.g., 'posthog')", max_length=100)),
                ('display_name', models.CharField(help_text='Clean repository name for display', max_length=200)),
                ('description', models.TextField(blank=True, default='', help_text='Short description from GitHub')),
                ('github_url', models.URLField(blank=True, default='', help_text='GitHub repository URL')),
                ('is_flagship', models.BooleanField(db_index=True, default=False, help_text='Whether this is a flagship repo shown prominently')),
                ('is_public', models.BooleanField(db_index=True, default=True, help_text='Whether this repo appears on public pages')),
                ('org_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repos', to='public.publicorgprofile')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_repo_profiles', to='teams.team')),
            ],
            options={
                'verbose_name': 'Public Repo Profile',
                'verbose_name_plural': 'Public Repo Profiles',
                'unique_together': {('org_profile', 'repo_slug')},
            },
        ),
        migrations.CreateModel(
            name='PublicRepoInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(help_text='LLM-generated insight narrative')),
                ('insight_type', models.CharField(help_text="Type of insight (e.g., 'weekly')", max_length=50)),
                ('is_current', models.BooleanField(db_index=True, default=False, help_text='Whether this is the active insight')),
                ('generated_at', models.DateTimeField(auto_now_add=True, help_text='When this insight was generated')),
                ('batch_id', models.CharField(blank=True, default='', help_text='Groq batch ID for traceability', max_length=100)),
                ('repo_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='public.publicrepoprofile')),
            ],
            options={
                'verbose_name': 'Public Repo Insight',
                'verbose_name_plural': 'Public Repo Insights',
            },
        ),
        migrations.CreateModel(
            name='PublicRepoStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('summary_window_days', models.IntegerField(default=30, help_text='Number of days in summary window')),
                ('trend_window_days', models.IntegerField(default=90, help_text='Number of days in trend window')),
                ('total_prs', models.IntegerField(default=0, help_text='Total merged PRs (all-time)')),
                ('total_prs_in_window', models.IntegerField(default=0, help_text='Merged PRs in summary window')),
                ('ai_assisted_pct', models.DecimalField(decimal_places=2, default=0, help_text='AI-assisted PR percentage in window', max_digits=5)),
                ('median_cycle_time_hours', models.DecimalField(decimal_places=2, default=0, help_text='Median cycle time in hours', max_digits=10)),
                ('median_review_time_hours', models.DecimalField(decimal_places=2, default=0, help_text='Median review time in hours', max_digits=10)),
                ('active_contributors_30d', models.IntegerField(default=0, help_text='Unique PR authors in last 30 days')),
                ('cadence_change_pct', models.DecimalField(decimal_places=2, default=0, help_text='Period-over-period PR volume change %', max_digits=7)),
                ('best_signal', models.JSONField(blank=True, default=dict, help_text='Most positive metric signal')),
                ('watchout_signal', models.JSONField(blank=True, default=dict, help_text='Most concerning metric signal')),
                ('trend_data', models.JSONField(blank=True, default=dict, help_text='90-day trend series for charts')),
                ('breakdown_data', models.JSONField(blank=True, default=dict, help_text='Tech/AI tools/PR type breakdowns')),
                ('recent_prs', models.JSONField(blank=True, default=list, help_text='Recent merged PRs for proof block')),
                ('benchmark_data', models.JSONField(blank=True, default=dict, help_text='Industry/peer benchmark context')),
                ('last_computed_at', models.DateTimeField(blank=True, help_text='When stats were last computed', null=True)),
                ('repo_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='public.publicrepoprofile')),
            ],
            options={
                'verbose_name': 'Public Repo Stats',
                'verbose_name_plural': 'Public Repo Stats',
            },
        ),
    ]
