# Generated by Django 5.2.9 on 2026-03-22 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_public_repo_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicrepoprofile',
            name='display_order',
            field=models.IntegerField(default=0, help_text='Sort order in listings (lower = first)'),
        ),
        migrations.AddField(
            model_name='publicrepoprofile',
            name='initial_backfill_days',
            field=models.PositiveIntegerField(default=180, help_text='Days of history to backfill on first sync'),
        ),
        migrations.AddField(
            model_name='publicrepoprofile',
            name='insights_enabled',
            field=models.BooleanField(default=False, help_text='Whether weekly LLM insights are generated'),
        ),
        migrations.AddField(
            model_name='publicrepoprofile',
            name='sync_enabled',
            field=models.BooleanField(db_index=True, default=True, help_text='Whether future syncs run for this repo'),
        ),
    ]
