# Generated by Django 5.2.9 on 2026-03-22 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0004_public_repo_catalog_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicRepoSyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending_backfill', 'Pending Backfill'), ('ready', 'Ready'), ('syncing', 'Syncing'), ('failed', 'Failed')], default='pending_backfill', max_length=20)),
                ('last_successful_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_attempted_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_updated_at', models.DateTimeField(blank=True, null=True)),
                ('checkpoint_payload', models.JSONField(blank=True, default=dict)),
                ('last_error', models.TextField(blank=True, default='')),
                ('last_backfill_completed_at', models.DateTimeField(blank=True, null=True)),
                ('repo_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sync_state', to='public.publicrepoprofile')),
            ],
            options={
                'verbose_name': 'Public Repo Sync State',
                'verbose_name_plural': 'Public Repo Sync States',
            },
        ),
    ]
