# Generated by Django 5.2.9 on 2026-03-22 16:48

from django.db import migrations


def seed_catalog_state(apps, schema_editor):
    """Seed insights_enabled from is_flagship and create sync states for existing profiles."""
    PublicRepoProfile = apps.get_model("public", "PublicRepoProfile")
    PublicRepoSyncState = apps.get_model("public", "PublicRepoSyncState")
    PublicRepoStats = apps.get_model("public", "PublicRepoStats")

    # Set insights_enabled=True where is_flagship=True
    PublicRepoProfile.objects.filter(is_flagship=True).update(insights_enabled=True)

    # Get IDs of profiles that already have stats (they were successfully syncing)
    profiles_with_stats = set(
        PublicRepoStats.objects.values_list("repo_profile_id", flat=True)
    )

    # Create sync states for all profiles that don't have one yet
    for profile in PublicRepoProfile.objects.all():
        if not PublicRepoSyncState.objects.filter(repo_profile_id=profile.pk).exists():
            status = "ready" if profile.pk in profiles_with_stats else "pending_backfill"
            PublicRepoSyncState.objects.create(
                repo_profile_id=profile.pk,
                status=status,
            )


def reverse_seed(apps, schema_editor):
    """Reverse: reset insights_enabled and delete auto-created sync states."""
    PublicRepoProfile = apps.get_model("public", "PublicRepoProfile")
    PublicRepoSyncState = apps.get_model("public", "PublicRepoSyncState")

    PublicRepoProfile.objects.all().update(insights_enabled=False)
    PublicRepoSyncState.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("public", "0005_public_repo_sync_state"),
    ]

    operations = [
        migrations.RunPython(seed_catalog_state, reverse_seed),
    ]
