# Generated by Django 5.2.9

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public", "0006_seed_catalog_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="publicorgstats",
            name="combined_trend_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Combined AI adoption + delivery trend for org. Shape: {"labels": [...], "datasets": {...}}',
            ),
        ),
        migrations.AddField(
            model_name="publicorgstats",
            name="ai_impact_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='AI vs non-AI impact comparison for org. Shape: {"ai_adoption_pct": float, "avg_cycle_with_ai": float|null, ...}',
            ),
        ),
        migrations.AddField(
            model_name="publicrepostats",
            name="combined_trend_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Combined AI adoption + delivery trend. Shape: {"labels": [...], "datasets": {"ai_adoption": {"values": [...]}, "cycle_time": {"values": [...]}}}',
            ),
        ),
        migrations.AddField(
            model_name="publicrepostats",
            name="correlation_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Correlation scatter and analysis. Shape: {"points": [{"x": float, "y": float, "week": str}], "r_value": float|null, "classification": str|null}',
            ),
        ),
        migrations.AddField(
            model_name="publicrepostats",
            name="ai_impact_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='AI vs non-AI impact comparison. Shape: {"ai_adoption_pct": float, "avg_cycle_with_ai": float|null, "avg_cycle_without_ai": float|null, "cycle_time_difference_pct": float|null, "total_prs": int, "ai_prs": int}',
            ),
        ),
        migrations.AddField(
            model_name="publicrepostats",
            name="comparison_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Repo vs org average deltas. Shape: {"ai_adoption_delta": float, "cycle_time_delta": float, "review_time_delta": float}',
            ),
        ),
    ]
