# Generated by Django 5.2.9 on 2026-03-22 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0007_add_trend_correlation_impact_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicorgstats',
            name='ai_impact_data',
            field=models.JSONField(blank=True, default=dict, help_text='AI vs non-AI impact comparison for org.'),
        ),
        migrations.AlterField(
            model_name='publicrepostats',
            name='ai_impact_data',
            field=models.JSONField(blank=True, default=dict, help_text='AI vs non-AI impact comparison stats.'),
        ),
        migrations.AlterField(
            model_name='publicrepostats',
            name='combined_trend_data',
            field=models.JSONField(blank=True, default=dict, help_text='Combined AI adoption + delivery trend for dual-axis chart.'),
        ),
        migrations.AlterField(
            model_name='publicrepostats',
            name='comparison_data',
            field=models.JSONField(blank=True, default=dict, help_text='Repo vs org average deltas for AI, cycle, review.'),
        ),
        migrations.AlterField(
            model_name='publicrepostats',
            name='correlation_data',
            field=models.JSONField(blank=True, default=dict, help_text='Correlation scatter: points, r_value, classification.'),
        ),
    ]
