# Generated by Django 5.2.9 on 2025-12-21 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('metrics', '0011_add_daily_insight'),
        ('teams', '0003_team_billing_details_last_changed_team_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('wrong_code', 'Generated wrong code'), ('missed_context', 'Missed project context'), ('style_issue', 'Style/formatting issue'), ('missing_tests', 'Forgot tests'), ('security', 'Security concern'), ('performance', 'Performance issue'), ('other', 'Other')], help_text='Type of issue encountered with AI-generated code', max_length=50, verbose_name='Category')),
                ('description', models.TextField(blank=True, help_text='Detailed description of what went wrong', verbose_name='Description')),
                ('file_path', models.CharField(blank=True, help_text='Path to the file with the issue', max_length=500, verbose_name='File path')),
                ('language', models.CharField(blank=True, help_text='Programming language of the problematic code', max_length=50, verbose_name='Language')),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], default='open', help_text='Current status of the feedback', max_length=20, verbose_name='Status')),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When the feedback was resolved', null=True, verbose_name='Resolved at')),
                ('pull_request', models.ForeignKey(blank=True, help_text='Associated pull request (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_feedback', to='metrics.pullrequest', verbose_name='Pull Request')),
                ('reported_by', models.ForeignKey(help_text='Team member who reported the issue', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_feedback', to='metrics.teammember', verbose_name='Reported by')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'verbose_name': 'AI Feedback',
                'verbose_name_plural': 'AI Feedback',
                'ordering': ['-created_at'],
            },
        ),
    ]
