# Generated by Django 5.2.9 on 2026-01-02 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
        ('metrics', '0035_add_jiraissue_description_labels_priority_parent'),
        ('teams', '0006_add_two_phase_onboarding_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.CharField(choices=[('engineering_insight', 'Engineering Insight'), ('pr_summary', 'PR Summary'), ('qa_answer', 'Q&A Answer'), ('ai_detection', 'AI Detection')], help_text='Type of LLM-generated content being rated', max_length=50, verbose_name='Content Type')),
                ('rating', models.BooleanField(help_text='Thumbs up (True) or thumbs down (False)', verbose_name='Rating')),
                ('comment', models.TextField(blank=True, default='', help_text='Optional detailed feedback about the content', verbose_name='Comment')),
                ('content_snapshot', models.JSONField(help_text='JSON snapshot of the LLM-generated content that was rated', verbose_name='Content Snapshot')),
                ('input_context', models.JSONField(blank=True, help_text='JSON snapshot of the input context used to generate the content', null=True, verbose_name='Input Context')),
                ('prompt_version', models.CharField(blank=True, default='', help_text='Version of the prompt template used', max_length=20, verbose_name='Prompt Version')),
                ('daily_insight', models.ForeignKey(blank=True, help_text='Associated daily insight (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_feedback', to='metrics.dailyinsight', verbose_name='Daily Insight')),
                ('pull_request', models.ForeignKey(blank=True, help_text='Associated pull request (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_feedback', to='metrics.pullrequest', verbose_name='Pull Request')),
                ('submitted_by', models.ForeignKey(blank=True, help_text='Team member who submitted the feedback', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_llm_feedback', to='metrics.teammember', verbose_name='Submitted By')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
                ('user', models.ForeignKey(help_text='User who submitted the feedback', on_delete=django.db.models.deletion.CASCADE, related_name='llm_feedback', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'LLM Feedback',
                'verbose_name_plural': 'LLM Feedback',
                'ordering': ['-created_at'],
            },
        ),
    ]
