# Generated by Django 5.2.9 on 2026-01-02 11:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_add_llm_feedback_model'),
        ('metrics', '0035_add_jiraissue_description_labels_priority_parent'),
        ('teams', '0006_add_two_phase_onboarding_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='llmfeedback',
            name='content_id',
            field=models.CharField(default='', help_text='ID of the content being rated', max_length=255, verbose_name='Content ID'),
        ),
        migrations.AddIndex(
            model_name='llmfeedback',
            index=models.Index(fields=['content_type'], name='llm_fb_content_type_idx'),
        ),
        migrations.AddIndex(
            model_name='llmfeedback',
            index=models.Index(fields=['rating'], name='llm_fb_rating_idx'),
        ),
        migrations.AddIndex(
            model_name='llmfeedback',
            index=models.Index(fields=['team', 'created_at'], name='llm_fb_team_created_idx'),
        ),
        migrations.AddIndex(
            model_name='llmfeedback',
            index=models.Index(fields=['team', 'content_type', 'rating'], name='llm_fb_team_type_rate_idx'),
        ),
    ]
