# Generated by Django 5.2.9 on 2026-01-02 11:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_add_content_id_to_llm_feedback'),
        ('metrics', '0035_add_jiraissue_description_labels_priority_parent'),
        ('teams', '0006_add_two_phase_onboarding_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='llmfeedback',
            constraint=models.UniqueConstraint(fields=('team', 'user', 'content_type', 'content_id'), name='llm_fb_unique_user_content'),
        ),
    ]
