# Generated by Django 5.2.9 on 2025-12-29 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_team_billing_details_last_changed_team_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='onboarding_complete',
            field=models.BooleanField(default=True, help_text='Whether the team has completed the onboarding flow. Default True for existing teams; set False during onboarding creation.'),
        ),
    ]
