# Generated by Django 5.2.9 on 2025-12-29 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_add_onboarding_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='onboarding_pipeline_completed_at',
            field=models.DateTimeField(blank=True, help_text='When the pipeline completed (success or failure).', null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='onboarding_pipeline_error',
            field=models.TextField(blank=True, help_text='Error message if pipeline failed.', null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='onboarding_pipeline_started_at',
            field=models.DateTimeField(blank=True, help_text='When the pipeline started processing.', null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='onboarding_pipeline_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('syncing', 'Syncing PRs'), ('llm_processing', 'Analyzing with AI'), ('computing_metrics', 'Computing Metrics'), ('computing_insights', 'Computing Insights'), ('complete', 'Complete'), ('failed', 'Failed')], default='not_started', help_text='Current status of the onboarding data processing pipeline.', max_length=50),
        ),
    ]
