# Generated by Django 5.2.9 on 2026-01-01 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_add_pipeline_tracking_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='background_llm_progress',
            field=models.IntegerField(default=0, help_text='Progress of Phase 2 background LLM analysis (0-100%).'),
        ),
        migrations.AddField(
            model_name='team',
            name='background_sync_progress',
            field=models.IntegerField(default=0, help_text='Progress of Phase 2 background sync (0-100%).'),
        ),
        migrations.AlterField(
            model_name='team',
            name='onboarding_pipeline_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('syncing', 'Syncing PRs'), ('llm_processing', 'Analyzing with AI'), ('computing_metrics', 'Computing Metrics'), ('computing_insights', 'Computing Insights'), ('phase1_complete', 'Dashboard Ready'), ('background_syncing', 'Background: Syncing'), ('background_llm', 'Background: Analyzing'), ('complete', 'Complete'), ('failed', 'Failed')], default='not_started', help_text='Current status of the onboarding data processing pipeline.', max_length=50),
        ),
    ]
