# Generated by Django 5.2.9 on 2026-01-03 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_add_integration_flags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='onboarding_pipeline_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('syncing_members', 'Syncing Team Members'), ('syncing', 'Syncing PRs'), ('llm_processing', 'Analyzing with AI'), ('computing_metrics', 'Computing Metrics'), ('computing_insights', 'Computing Insights'), ('phase1_complete', 'Dashboard Ready'), ('background_syncing', 'Background: Syncing'), ('background_llm', 'Background: Analyzing'), ('complete', 'Complete'), ('failed', 'Failed')], default='not_started', help_text='Current status of the onboarding data processing pipeline.', max_length=50),
        ),
    ]
