# Generated by Django 5.2.9 on 2026-01-11 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0009_add_syncing_members_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='copilot_consecutive_failures',
            field=models.PositiveIntegerField(default=0, help_text='Count of consecutive sync failures (reset on success)'),
        ),
        migrations.AddField(
            model_name='team',
            name='copilot_last_sync_at',
            field=models.DateTimeField(blank=True, help_text='Last successful Copilot data sync', null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='copilot_status',
            field=models.CharField(choices=[('disabled', 'Not Connected'), ('connected', 'Connected'), ('insufficient_licenses', 'Awaiting Data'), ('token_revoked', 'Reconnection Required')], default='disabled', help_text='Current Copilot integration status', max_length=30),
        ),
    ]
