# Generated by Django 5.2.9 on 2026-01-25 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0011_alter_team_onboarding_pipeline_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='copilot_price_tier',
            field=models.CharField(choices=[('individual', 'Individual ($10/seat)'), ('business', 'Business ($19/seat)'), ('enterprise', 'Enterprise ($39/seat)')], default='business', help_text='Copilot subscription tier for cost calculations', max_length=20),
        ),
    ]
