/* tslint:disable */
/* eslint-disable */
/**
 * tformance
 * The most amazing SaaS application the world has ever seen
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AggregateEmployeeData
 */
export interface AggregateEmployeeData {
    /**
     * 
     * @type {any}
     * @memberof AggregateEmployeeData
     */
    totalCosts: any | null;
    /**
     * 
     * @type {any}
     * @memberof AggregateEmployeeData
     */
    averageSalaries: any | null;
    /**
     * 
     * @type {any}
     * @memberof AggregateEmployeeData
     */
    headcounts: any | null;
}

/**
 * Check if a given object implements the AggregateEmployeeData interface.
 */
export function instanceOfAggregateEmployeeData(value: object): value is AggregateEmployeeData {
    if (!('totalCosts' in value) || value['totalCosts'] === undefined) return false;
    if (!('averageSalaries' in value) || value['averageSalaries'] === undefined) return false;
    if (!('headcounts' in value) || value['headcounts'] === undefined) return false;
    return true;
}

export function AggregateEmployeeDataFromJSON(json: any): AggregateEmployeeData {
    return AggregateEmployeeDataFromJSONTyped(json, false);
}

export function AggregateEmployeeDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): AggregateEmployeeData {
    if (json == null) {
        return json;
    }
    return {
        
        'totalCosts': json['total_costs'],
        'averageSalaries': json['average_salaries'],
        'headcounts': json['headcounts'],
    };
}

  export function AggregateEmployeeDataToJSON(json: any): AggregateEmployeeData {
      return AggregateEmployeeDataToJSONTyped(json, false);
  }

  export function AggregateEmployeeDataToJSONTyped(value?: AggregateEmployeeData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total_costs': value['totalCosts'],
        'average_salaries': value['averageSalaries'],
        'headcounts': value['headcounts'],
    };
}

